# Generated by Django 2.2.3 on 2019-07-04 14:59

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Bank',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True, verbose_name='Название банка')),
            ],
        ),
        migrations.CreateModel(
            name='MortgageOffer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='Название предложения по ипотеке', max_length=255, unique=True, verbose_name='Название предложения')),
            ],
        ),
        migrations.CreateModel(
            name='MortgagePage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='Заголовок страницы по ипотеке пример: Материнский капитал, КорпорАктив, Военная ипотека...', max_length=255, unique=True, verbose_name='Заголовок')),
            ],
        ),
    ]
