# Generated by Django 2.2.3 on 2019-07-05 07:29

import ckeditor.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mortgage', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='bank',
            options={'verbose_name': 'Объект', 'verbose_name_plural': 'Объекты (Жилые, Коммерческие)'},
        ),
        migrations.AlterModelOptions(
            name='mortgageoffer',
            options={'verbose_name': 'Объект', 'verbose_name_plural': 'Объекты (Жилые, Коммерческие)'},
        ),
        migrations.AlterModelOptions(
            name='mortgagepage',
            options={'verbose_name': 'Объект', 'verbose_name_plural': 'Объекты (Жилые, Коммерческие)'},
        ),
        migrations.AddField(
            model_name='mortgageoffer',
            name='bank',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='mortgage.Bank', verbose_name='Банк'),
        ),
        migrations.AddField(
            model_name='mortgageoffer',
            name='description',
            field=ckeditor.fields.RichTextField(blank=True, help_text='Описание и дополнительные условия', null=True, verbose_name='Описание'),
        ),
        migrations.AddField(
            model_name='mortgageoffer',
            name='first_payment_from',
            field=models.FloatField(blank=True, default=None, null=True, verbose_name='Первоначальный взнос (от)'),
        ),
        migrations.AddField(
            model_name='mortgageoffer',
            name='first_payment_to',
            field=models.FloatField(blank=True, default=None, null=True, verbose_name='Первоначальный взнос (до)'),
        ),
        migrations.AddField(
            model_name='mortgageoffer',
            name='loan_term_from',
            field=models.PositiveIntegerField(blank=True, default=None, null=True, verbose_name='Срок кредита (лет) (от)'),
        ),
        migrations.AddField(
            model_name='mortgageoffer',
            name='loan_term_to',
            field=models.PositiveIntegerField(blank=True, default=None, null=True, verbose_name='Срок кредита (лет) (до)'),
        ),
        migrations.AlterField(
            model_name='mortgageoffer',
            name='title',
            field=models.CharField(help_text='Название ипотечного кредита', max_length=255, unique=True, verbose_name='Название программы'),
        ),
    ]
