# Generated by Django 2.2.3 on 2019-07-15 12:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mortgage', '0002_auto_20190710_1242'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='waytobuy',
            options={'verbose_name': 'Способы покупки (Военная ипотека, Мат. капитал)', 'verbose_name_plural': 'Способы покупки (Военная ипотека, Мат. капитал)'},
        ),
        migrations.AddField(
            model_name='offer',
            name='loan_payment_monthly',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True, verbose_name='Ежемесячный платеж'),
        ),
        migrations.AlterField(
            model_name='waytobuy',
            name='military',
            field=models.ManyToManyField(blank=True, help_text='Выберите Объекты подходящие под военную ипотеку', related_name='mortgage_object_military', to='realty.Object', verbose_name='Военная ипотека'),
        ),
        migrations.AlterField(
            model_name='waytobuy',
            name='mother',
            field=models.ManyToManyField(blank=True, help_text='Выберите Объекты подходящие под материнский капитал', related_name='mortgage_object_mother', to='realty.Object', verbose_name='Материнский капитал'),
        ),
    ]
