# Generated by Django 2.2.3 on 2019-07-05 07:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mortgage', '0002_auto_20190705_1029'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='bank',
            options={'verbose_name': 'Банк', 'verbose_name_plural': 'Банки'},
        ),
        migrations.AlterModelOptions(
            name='mortgageoffer',
            options={'verbose_name': 'Ипотечная программа', 'verbose_name_plural': 'Ипотечные программы'},
        ),
        migrations.AlterModelOptions(
            name='mortgagepage',
            options={'verbose_name': 'Страница (Ипотека)', 'verbose_name_plural': 'Страницы (Ипотека)'},
        ),
        migrations.AlterField(
            model_name='mortgageoffer',
            name='first_payment_from',
            field=models.DecimalField(blank=True, decimal_places=2, default=None, max_digits=5, null=True, verbose_name='от'),
        ),
        migrations.AlterField(
            model_name='mortgageoffer',
            name='first_payment_to',
            field=models.DecimalField(blank=True, decimal_places=2, default=None, max_digits=5, null=True, verbose_name='до'),
        ),
        migrations.AlterField(
            model_name='mortgageoffer',
            name='loan_term_from',
            field=models.PositiveIntegerField(blank=True, default=None, null=True, verbose_name='от'),
        ),
        migrations.AlterField(
            model_name='mortgageoffer',
            name='loan_term_to',
            field=models.PositiveIntegerField(blank=True, default=None, null=True, verbose_name='до'),
        ),
    ]
