# Generated by Django 2.2.3 on 2019-07-05 08:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mortgage', '0003_auto_20190705_1048'),
    ]

    operations = [
        migrations.AddField(
            model_name='mortgageoffer',
            name='interest_rate_from',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=2, null=True, verbose_name='от'),
        ),
        migrations.AddField(
            model_name='mortgageoffer',
            name='interest_rate_to',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=2, null=True, verbose_name='до'),
        ),
        migrations.AlterField(
            model_name='mortgageoffer',
            name='bank',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='mortgage.Bank', verbose_name='Банк'),
        ),
        migrations.AlterField(
            model_name='mortgageoffer',
            name='first_payment_from',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=2, null=True, verbose_name='от'),
        ),
        migrations.AlterField(
            model_name='mortgageoffer',
            name='first_payment_to',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=2, null=True, verbose_name='до'),
        ),
        migrations.AlterField(
            model_name='mortgageoffer',
            name='loan_term_from',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='от'),
        ),
        migrations.AlterField(
            model_name='mortgageoffer',
            name='loan_term_to',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='до'),
        ),
    ]
