# Generated by Django 2.2.3 on 2019-07-05 08:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mortgage', '0004_auto_20190705_1100'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mortgageoffer',
            name='first_payment_from',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=4, null=True, verbose_name='от'),
        ),
        migrations.AlterField(
            model_name='mortgageoffer',
            name='first_payment_to',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=4, null=True, verbose_name='до'),
        ),
        migrations.AlterField(
            model_name='mortgageoffer',
            name='interest_rate_from',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=4, null=True, verbose_name='от'),
        ),
        migrations.AlterField(
            model_name='mortgageoffer',
            name='interest_rate_to',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=4, null=True, verbose_name='до'),
        ),
    ]
