# Generated by Django 2.2.3 on 2019-07-05 08:53

import apps.mortgage.models
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mortgage', '0005_auto_20190705_1102'),
    ]

    operations = [
        migrations.AddField(
            model_name='bank',
            name='logo',
            field=models.FileField(blank=True, null=True, upload_to=apps.mortgage.models.logo_upload_path, validators=[django.core.validators.FileExtensionValidator(['svg'])], verbose_name='Логотип банка .svg'),
        ),
        migrations.AlterField(
            model_name='mortgageoffer',
            name='loan_term_from',
            field=models.PositiveIntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(50)], verbose_name='от'),
        ),
        migrations.AlterField(
            model_name='mortgageoffer',
            name='loan_term_to',
            field=models.PositiveIntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(50)], verbose_name='до'),
        ),
    ]
