# Generated by Django 2.2.3 on 2019-07-05 11:58

import apps.mortgage.models
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('realty', '0006_auto_20190705_1102'),
        ('mortgage', '0006_auto_20190705_1153'),
    ]

    operations = [
        migrations.AddField(
            model_name='mortgageoffer',
            name='objects',
            field=models.ManyToManyField(blank=True, to='realty.Object', verbose_name='Объекты'),
        ),
        migrations.AlterField(
            model_name='bank',
            name='logo',
            field=models.FileField(blank=True, null=True, upload_to=apps.mortgage.models.logo_upload_path, validators=[django.core.validators.FileExtensionValidator(['svg'])], verbose_name='Логотип банка (.svg)'),
        ),
        migrations.AlterField(
            model_name='mortgageoffer',
            name='bank',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mortgage.Bank', verbose_name='Банк'),
        ),
    ]
