# Generated by Django 2.2.3 on 2019-07-05 12:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mortgage', '0007_auto_20190705_1458'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mortgageoffer',
            name='objects',
            field=models.ManyToManyField(blank=True, default=None, to='realty.Object', verbose_name='Объекты'),
        ),
    ]
