# Generated by Django 2.2.3 on 2019-07-08 06:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mortgage', '0008_auto_20190705_1506'),
    ]

    operations = [
        migrations.DeleteModel(
            name='MortgagePage',
        ),
        migrations.AlterField(
            model_name='mortgageoffer',
            name='objects',
            field=models.ManyToManyField(blank=True, to='realty.Object', verbose_name='Объекты'),
        ),
    ]
