# Generated by Django 2.2.3 on 2019-07-09 13:50

import apps.mortgage.models
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mortgage', '0009_auto_20190708_0928'),
    ]

    operations = [
        migrations.RenameField(
            model_name='mortgageoffer',
            old_name='interest_rate_from',
            new_name='rate_from',
        ),
        migrations.RenameField(
            model_name='mortgageoffer',
            old_name='interest_rate_to',
            new_name='rate_to',
        ),
        migrations.AlterField(
            model_name='bank',
            name='logo',
            field=models.FileField(blank=True, null=True, upload_to=apps.mortgage.models.logo_upload_path, validators=[django.core.validators.FileExtensionValidator(['svg', 'png'])], verbose_name='Логотип банка (svg, png)'),
        ),
    ]
