# Generated by Django 2.2.3 on 2019-07-09 14:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mortgage', '0010_auto_20190709_1650'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mortgageoffer',
            name='title',
            field=models.CharField(help_text='Название ипотечного кредита', max_length=255, verbose_name='Название программы'),
        ),
    ]
