# Generated by Django 2.2.4 on 2019-08-28 08:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0002_auto_20190826_1920'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='newscategory',
            options={'verbose_name': 'Новостная категория', 'verbose_name_plural': 'Категории новостей'},
        ),
    ]
