# Generated by Django 2.2.4 on 2019-08-19 14:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0002_auto_20190731_1555'),
    ]

    operations = [
        migrations.AddField(
            model_name='news',
            name='active',
            field=models.BooleanField(default=True, help_text='Опубликована на сайте', verbose_name='Активная'),
        ),
    ]
