# Generated by Django 2.2.5 on 2019-09-30 07:12

import apps.news.models.actions
from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0003_auto_20190930_0947'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='action',
            options={'verbose_name': 'Акция', 'verbose_name_plural': 'Акции'},
        ),
        migrations.RemoveField(
            model_name='action',
            name='date_test',
        ),
        migrations.AddField(
            model_name='action',
            name='image_for_card',
            field=models.ImageField(blank=True, null=True, upload_to=apps.news.models.actions.actions_image_upload_path, verbose_name='Изображение для карточки'),
        ),
        migrations.AddField(
            model_name='action',
            name='image_for_detail',
            field=models.ImageField(blank=True, null=True, upload_to=apps.news.models.actions.actions_image_upload_path, verbose_name='Изображение для страницы'),
        ),
        migrations.AlterField(
            model_name='action',
            name='date_end',
            field=models.DateField(default=django.utils.timezone.now, verbose_name='Дата окончания акции'),
        ),
        migrations.AlterField(
            model_name='action',
            name='date_start',
            field=models.DateField(default=django.utils.timezone.now, verbose_name='Дата начала акции'),
        ),
    ]
