# Generated by Django 2.2.1 on 2019-06-03 15:56

import apps.news.models
from django.db import migrations
import imagekit.models.fields


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0003_auto_20190603_1848'),
    ]

    operations = [
        migrations.AlterField(
            model_name='news',
            name='main_image',
            field=imagekit.models.fields.ProcessedImageField(upload_to=apps.news.models.image_upload_path),
        ),
    ]
