# Generated by Django 2.2.5 on 2019-09-30 07:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0004_auto_20190930_1012'),
    ]

    operations = [
        migrations.AlterField(
            model_name='action',
            name='date_end',
            field=models.DateField(blank=True, null=True, verbose_name='Дата окончания акции'),
        ),
    ]
