# Generated by Django 2.2.5 on 2019-09-30 08:38

import apps.news.models.actions
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0005_auto_20190930_1021'),
    ]

    operations = [
        migrations.CreateModel(
            name='ActionPartner',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Название партнера')),
                ('logo', models.ImageField(blank=True, null=True, upload_to=apps.news.models.actions.actions_partner_logo_upload_path, verbose_name='Логотип партнера акции')),
                ('site_url', models.URLField(blank=True, help_text='Url сайта партнера', null=True, verbose_name='Сайт партнера')),
                ('action', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='news.Action', verbose_name='Акция')),
            ],
            options={
                'verbose_name': 'Партнер акции',
                'verbose_name_plural': 'Партнеры акций',
            },
        ),
    ]
