# Generated by Django 2.2.1 on 2019-06-03 15:59

import apps.news.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0006_auto_20190603_1857'),
    ]

    operations = [
        migrations.AlterField(
            model_name='news',
            name='main_image',
            field=models.ImageField(blank=True, null=True, upload_to=apps.news.models.image_upload_path, verbose_name='Главное изображение'),
        ),
    ]
