# Generated by Django 2.2.5 on 2019-09-30 11:11

import apps.news.models.actions
from django.db import migrations
import imagekit.models.fields


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0006_actionpartner'),
    ]

    operations = [
        migrations.AlterField(
            model_name='action',
            name='image_for_card',
            field=imagekit.models.fields.ProcessedImageField(blank=True, null=True, upload_to=apps.news.models.actions.actions_image_upload_path, verbose_name='Изображение для карточки'),
        ),
    ]
