# Generated by Django 2.2.1 on 2019-06-03 16:01

import apps.news.models
from django.db import migrations, models
import imagekit.models.fields


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0007_auto_20190603_1859'),
    ]

    operations = [
        migrations.AddField(
            model_name='news',
            name='main_image_proc',
            field=imagekit.models.fields.ProcessedImageField(blank=True, null=True, upload_to=apps.news.models.main_image_upload_path),
        ),
        migrations.AlterField(
            model_name='news',
            name='main_image',
            field=models.ImageField(blank=True, null=True, upload_to=apps.news.models.main_image_upload_path, verbose_name='Главное изображение'),
        ),
    ]
