# Generated by Django 2.2.5 on 2019-09-30 12:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0007_auto_20190930_1411'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Action',
            new_name='Actions',
        ),
        migrations.RenameModel(
            old_name='ActionPartner',
            new_name='ActionsPartner',
        ),
    ]
