# Generated by Django 2.2.1 on 2019-06-06 08:08

import apps.news.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0009_auto_20190603_2224'),
    ]

    operations = [
        migrations.AlterField(
            model_name='news',
            name='main_image',
            field=models.ImageField(blank=True, null=True, upload_to=apps.news.models.main_image_upload_path, verbose_name='Главное изображение'),
        ),
    ]
