# Generated by Django 2.2.1 on 2019-06-06 10:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0010_auto_20190606_1108'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='news',
            name='created',
        ),
    ]
