# Generated by Django 2.2 on 2019-04-04 11:28

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Object',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('active', models.BooleanField(default=True, verbose_name='Активный')),
                ('completed', models.BooleanField(default=False, verbose_name='Реализован')),
                ('name', models.CharField(db_index=True, max_length=255, verbose_name='Название объекта')),
                ('slug', models.SlugField(max_length=100, verbose_name='URL Slug')),
            ],
            options={
                'verbose_name': 'Объект',
                'verbose_name_plural': 'Объекты',
            },
        ),
    ]
