# Generated by Django 2.2.6 on 2019-10-30 10:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('realty', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='objectcommercialsite',
            name='site_type',
            field=models.CharField(choices=[('office', 'Офис'), ('free-use', 'Помещение свободного назначения')], max_length=100, verbose_name='Тип помещения'),
        ),
    ]
