# Generated by Django 2.2.6 on 2019-10-25 14:21

import ckeditor.fields
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('realty', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='objectblock',
            options={'verbose_name': 'Блок Объекта', 'verbose_name_plural': 'Объект (Блоки)'},
        ),
        migrations.RemoveField(
            model_name='objectcommercial',
            name='object',
        ),
        migrations.RemoveField(
            model_name='objectcommercial',
            name='object_blocks',
        ),
        migrations.RemoveField(
            model_name='objectcommercial',
            name='object_sections',
        ),
        migrations.AddField(
            model_name='objectcommercial',
            name='active',
            field=models.BooleanField(default=True, help_text='Опубликован на сайте', verbose_name='Активный'),
        ),
        migrations.AddField(
            model_name='objectcommercial',
            name='address',
            field=models.CharField(blank=True, help_text='Город, улица, номер дома (для завершенных/построенных объектов)', max_length=255, null=True, verbose_name='Адрес'),
        ),
        migrations.AddField(
            model_name='objectcommercial',
            name='all_sold',
            field=models.BooleanField(default=False, help_text='Все квартиры и помещения проданы', verbose_name='Все помещения проданы'),
        ),
        migrations.AddField(
            model_name='objectcommercial',
            name='building_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='realty.ObjectBuildingTypes', verbose_name='Тип Здания'),
        ),
        migrations.AddField(
            model_name='objectcommercial',
            name='completed',
            field=models.BooleanField(default=False, verbose_name='Строительство завершено'),
        ),
        migrations.AddField(
            model_name='objectcommercial',
            name='crm_id',
            field=models.CharField(default=1, help_text='ID объекта в 1C (Заполняется автоматически при выгрузке)', max_length=100, unique=True, verbose_name='CRM ID'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='objectcommercial',
            name='description',
            field=ckeditor.fields.RichTextField(blank=True, null=True, verbose_name='Описание'),
        ),
        migrations.AddField(
            model_name='objectcommercial',
            name='name',
            field=models.CharField(db_index=True, default=1, max_length=255, unique=True, verbose_name='Название объекта'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='objectcommercial',
            name='object_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='realty.ObjectTypes', verbose_name='Тип Объекта'),
        ),
        migrations.AddField(
            model_name='objectcommercial',
            name='order',
            field=models.PositiveIntegerField(blank=True, default=0, help_text='Чем выше число, тем ниже объект в списке', null=True, verbose_name='Порядок'),
        ),
        migrations.AddField(
            model_name='objectcommercial',
            name='slug',
            field=models.SlugField(default=1, help_text='e.g.: status-house (max 100 chars), получим https://monolit.site/commercial/status-house/', max_length=100, unique=True, verbose_name='URL адрес'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='objectblock',
            name='name',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Название блока'),
        ),
        migrations.AlterField(
            model_name='objectsection',
            name='floor_first',
            field=models.IntegerField(blank=True, help_text='мин. этаж: -5', null=True, validators=[django.core.validators.MinValueValidator(-5), django.core.validators.MaxValueValidator(1)], verbose_name='Этаж Первый'),
        ),
    ]
