# Generated by Django 2.2.7 on 2019-11-28 09:28

import apps.realty.models.object_commercial_site
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('realty', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='objectcommercialsite',
            name='image_floor',
            field=models.ImageField(blank=True, help_text='Планировка квартиры на этаже', null=True, upload_to=apps.realty.models.object_commercial_site.image_upload_path, verbose_name='Квартира на этаже'),
        ),
        migrations.AddField(
            model_name='objectcommercialsite',
            name='image_genplan',
            field=models.ImageField(blank=True, help_text='Выделенный дом на генплане', null=True, upload_to=apps.realty.models.object_commercial_site.image_upload_path, verbose_name='Дом на генплане'),
        ),
        migrations.AddField(
            model_name='objectcommercialsite',
            name='image_section',
            field=models.ImageField(blank=True, help_text='Выделенный этаж в секции объекта', null=True, upload_to=apps.realty.models.object_commercial_site.image_upload_path, verbose_name='Этаж в секции'),
        ),
        migrations.AddField(
            model_name='objectcommercialsite',
            name='image_section_in_object',
            field=models.ImageField(blank=True, help_text='Выделенная секция в доме', null=True, upload_to=apps.realty.models.object_commercial_site.image_upload_path, verbose_name='Секция в доме'),
        ),
    ]
