# Generated by Django 2.2.6 on 2019-10-04 12:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('realty', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='object',
            name='category',
        ),
        migrations.RemoveField(
            model_name='object',
            name='city',
        ),
        migrations.RemoveField(
            model_name='object',
            name='object_type',
        ),
        migrations.DeleteModel(
            name='ObjectCategory',
        ),
    ]
