# Generated by Django 2.2.1 on 2019-05-22 07:38

import apps.realty.models.object
import apps.realty.models.object_document
import apps.realty.models.object_file
import apps.realty.models.object_gallery
import apps.realty.models.object_info_tab
import apps.realty.models.object_site
import ckeditor.fields
import datetime
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import location_field.models.plain


class Migration(migrations.Migration):

    dependencies = [
        ('realty', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ObjectBlock',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=255, null=True, verbose_name='Номер блока или его название')),
            ],
            options={
                'verbose_name': 'Блок Объекта',
                'verbose_name_plural': 'Объект Блоки',
            },
        ),
        migrations.CreateModel(
            name='ObjectCategory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Название категории')),
            ],
        ),
        migrations.CreateModel(
            name='ObjectDocumentAuthor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Пример: Иванов В.А.', max_length=255, verbose_name='Автор')),
            ],
            options={
                'verbose_name': 'Автор документа',
                'verbose_name_plural': 'Авторы документов',
            },
        ),
        migrations.CreateModel(
            name='ObjectGallery',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.PositiveIntegerField(blank=True, default=0, help_text='Чем выше число, тем ниже объект в списке', null=True, verbose_name='Порядок')),
                ('name', models.CharField(max_length=255, verbose_name='Заголовок галереи')),
                ('updated', models.DateTimeField(auto_now=True, null=True)),
            ],
            options={
                'verbose_name': 'Галерея Объекта',
                'verbose_name_plural': 'Объекты (Фото Галереи этапов строительства)',
            },
        ),
        migrations.CreateModel(
            name='ObjectSection',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Номер секции или её название')),
                ('genplan_svg', models.TextField(blank=True, help_text='Выеделение с помощью SVG координат секции на Генплане', null=True, verbose_name='SVG координары выделения секции на Генплане')),
                ('year_of_construction', models.PositiveIntegerField(blank=True, default=2019, help_text='Допустимые значения от 2019 до 2100', null=True, validators=[django.core.validators.MinValueValidator(2019), django.core.validators.MaxValueValidator(2100)], verbose_name='Год сдачи')),
                ('floor_start', models.IntegerField(blank=True, help_text='мин. этаж: -5', null=True, validators=[django.core.validators.MinValueValidator(-5), django.core.validators.MaxValueValidator(0)], verbose_name='Этаж Первый')),
                ('floor_end', models.IntegerField(blank=True, help_text='макс. этаж: 100', null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)], verbose_name='Этаж Последний')),
            ],
            options={
                'verbose_name': 'Секция Объекта',
                'verbose_name_plural': 'Объекты (Секции)',
            },
        ),
        migrations.CreateModel(
            name='ObjectSiteWindowsView',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Вид из окон')),
            ],
        ),
        migrations.AlterModelOptions(
            name='object',
            options={'verbose_name': 'Объект', 'verbose_name_plural': 'Объекты (Жилые, Коммерческие)'},
        ),
        migrations.AddField(
            model_name='object',
            name='address',
            field=models.CharField(blank=True, help_text='Город, улица, номер дома (для завершенных/построенных объектов)', max_length=255, null=True, verbose_name='Адрес'),
        ),
        migrations.AddField(
            model_name='object',
            name='building_type',
            field=models.CharField(blank=True, choices=[('monolith', 'Монолитный'), ('monolith_frame', 'Монолитно-каркасный'), ('panel', 'Панельный')], max_length=100, null=True, verbose_name='Тип Здания'),
        ),
        migrations.AddField(
            model_name='object',
            name='city',
            field=models.CharField(blank=True, choices=[('alushta', 'Алушта'), ('evpatoriya', 'Евпатория'), ('simferopol', 'Симферополь'), ('yalta', 'Ялта')], max_length=100, null=True, verbose_name='Город'),
        ),
        migrations.AddField(
            model_name='object',
            name='crm_id',
            field=models.CharField(default=1, help_text='ID объекта в 1C (Заполняется автоматически при выгрузке)', max_length=100, unique=True, verbose_name='CRM ID'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='object',
            name='description',
            field=ckeditor.fields.RichTextField(blank=True, null=True, verbose_name='Описание'),
        ),
        migrations.AddField(
            model_name='object',
            name='genplan',
            field=models.ImageField(blank=True, help_text='Изображение с генпланом', null=True, upload_to=apps.realty.models.object.genplan_upload_path, verbose_name='Генплан'),
        ),
        migrations.AddField(
            model_name='object',
            name='has_military',
            field=models.BooleanField(default=False, help_text='Подходит ли данный объект для военной ипотеки', verbose_name='Военная ипотека'),
        ),
        migrations.AddField(
            model_name='object',
            name='has_mother',
            field=models.BooleanField(default=False, help_text='Подходит ли данный объект под оплату мат.капиталом', verbose_name='Материнский капитал'),
        ),
        migrations.AddField(
            model_name='object',
            name='location',
            field=location_field.models.plain.PlainLocationField(blank=True, default='44.952117,34.10241700000006', help_text='Географические координаты - широта и долгота', max_length=63, null=True, verbose_name='Локация'),
        ),
        migrations.AddField(
            model_name='object',
            name='main_image',
            field=models.ImageField(blank=True, null=True, upload_to=apps.realty.models.object.image_upload_path, verbose_name='Главное изображение'),
        ),
        migrations.AddField(
            model_name='object',
            name='object_type',
            field=models.CharField(blank=True, choices=[('business_center', 'Бизнес центр'), ('city', 'Город'), ('living_house', 'Жилой дом'), ('living_quarter', 'Жилой квартал'), ('living_complex', 'Жилой комплекс'), ('resort_complex', 'Курортный комплекс'), ('multipurposes_complex', 'Многофункциональный комплекс'), ('family_quarter', 'Семейный квартал'), ('business_and_retail_center', 'Торгово-офисный центр'), ('mall', 'Торговый центр')], max_length=100, null=True, verbose_name='Тип Объекта'),
        ),
        migrations.AddField(
            model_name='object',
            name='order',
            field=models.PositiveIntegerField(blank=True, default=0, help_text='Чем выше число, тем ниже объект в списке', null=True, verbose_name='Порядок'),
        ),
        migrations.AddField(
            model_name='object',
            name='panoram',
            field=models.URLField(blank=True, help_text='e.g.: https://monolit360.com/files/main/index.html?s=pano1692', null=True, verbose_name='Cсылка на панораму'),
        ),
        migrations.AddField(
            model_name='object',
            name='updated',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
        migrations.AddField(
            model_name='object',
            name='webcam',
            field=models.URLField(blank=True, help_text='e.g.: https://rtsp.me/embed/3KASrTkG/', null=True, verbose_name='Cсылка на web-камеру'),
        ),
        migrations.AlterField(
            model_name='object',
            name='active',
            field=models.BooleanField(default=True, help_text='Опубликован на сайте', verbose_name='Активный'),
        ),
        migrations.AlterField(
            model_name='object',
            name='completed',
            field=models.BooleanField(default=False, verbose_name='Строительство завершено'),
        ),
        migrations.AlterField(
            model_name='object',
            name='name',
            field=models.CharField(db_index=True, max_length=255, unique=True, verbose_name='Название объекта'),
        ),
        migrations.AlterField(
            model_name='object',
            name='slug',
            field=models.SlugField(help_text='e.g.: status-house (max 100 chars), получим https://monolit.site/objects/status-house/', max_length=100, unique=True, verbose_name='URL адрес'),
        ),
        migrations.CreateModel(
            name='ObjectVideo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=255, null=True, verbose_name='Заголовок видео')),
                ('video_url', models.URLField(blank=True, help_text='e.g.: https://youtu.be/JbacFR_B-jw', null=True, verbose_name='Cсылка на видео в YouTube')),
                ('created', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated', models.DateTimeField(auto_now=True, null=True)),
                ('object', models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='realty.Object')),
            ],
            options={
                'verbose_name': 'Видео',
                'verbose_name_plural': 'Видео',
            },
        ),
        migrations.CreateModel(
            name='ObjectSite',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.BooleanField(default=True, help_text='Опубликован на сайте', verbose_name='Активный')),
                ('special_offer', models.BooleanField(default=False, verbose_name='Спецпредложение')),
                ('site_type', models.CharField(blank=True, choices=[('flat', 'Квартира'), ('apartments', 'Апартаменты'), ('commercial', 'Коммерческое помещение')], max_length=100, null=True, verbose_name='Тип помещения')),
                ('crm_id', models.CharField(help_text='ID объекта в 1C (Заполняется автоматически при выгрузке)', max_length=100, unique=True, verbose_name='CRM ID')),
                ('floor', models.IntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(-5), django.core.validators.MaxValueValidator(100)], verbose_name='Этаж')),
                ('site_number', models.CharField(blank=True, max_length=100, null=True, verbose_name='Номер квартиры или помещения')),
                ('price_per_square', models.DecimalField(blank=True, decimal_places=2, help_text='Стоимость одного квадратного метра', max_digits=20, null=True, verbose_name='Цена за м2 (руб.)')),
                ('price_total', models.DecimalField(blank=True, decimal_places=2, help_text='Считается автоматически из Площади помещения * Цена за м2', max_digits=30, null=True, verbose_name='Общая стоимость (руб.)')),
                ('rooms_qty', models.CharField(blank=True, choices=[('0', 'Студия'), ('1', '1'), ('2', '2'), ('3', '3'), ('4', '4'), ('5', '5')], max_length=100, null=True, verbose_name='Количество комнат в помещении')),
                ('site_area', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Площадь помещения')),
                ('living_area', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Жилая площадь')),
                ('kitchen_area', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Площадь кухни')),
                ('ceiling_height', models.DecimalField(blank=True, decimal_places=2, help_text='Пример: 2.30 = 2 метра 30 см', max_digits=10, null=True, verbose_name='Высота потолков (м)')),
                ('two_levels', models.BooleanField(default=False, help_text='Квартира с полноценным 2-м этажом', verbose_name='Двухуровневая квартира')),
                ('entresol', models.BooleanField(default=False, help_text='Наличие в квартире этажа-антресоли', verbose_name='Антресоль')),
                ('wardrobe', models.BooleanField(default=False, help_text='Помещение для гардеробной или кладовой', verbose_name='Гардеробная')),
                ('finish_type', models.CharField(blank=True, choices=[('0', 'Без отделки'), ('1', 'Черновая отделка'), ('1', 'Чистовая отделка')], max_length=100, null=True, verbose_name='Отделка')),
                ('image_planning', models.ImageField(blank=True, null=True, upload_to=apps.realty.models.object_site.image_upload_path, verbose_name='Планировка')),
                ('image_planning3d', models.ImageField(blank=True, null=True, upload_to=apps.realty.models.object_site.image_upload_path, verbose_name='Планировка 3D')),
                ('image_floor', models.ImageField(blank=True, help_text='Планировка квартиры на этаже', null=True, upload_to=apps.realty.models.object_site.image_upload_path, verbose_name='Квартира на этаже')),
                ('image_section', models.ImageField(blank=True, help_text='Выделенный этаж в секции объекта', null=True, upload_to=apps.realty.models.object_site.image_upload_path, verbose_name='Этаж в секции')),
                ('image_section_in_object', models.ImageField(blank=True, help_text='Выделенная секция в доме', null=True, upload_to=apps.realty.models.object_site.image_upload_path, verbose_name='Секция в доме')),
                ('image_genplan', models.ImageField(blank=True, help_text='Выделенный дом на генплане', null=True, upload_to=apps.realty.models.object_site.image_upload_path, verbose_name='Дом на генплане')),
                ('updated', models.DateTimeField(auto_now=True, null=True)),
                ('object', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='realty.Object', verbose_name='Объект')),
                ('object_block', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='realty.ObjectBlock', verbose_name='Блок Объекта')),
                ('object_section', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='realty.ObjectSection', verbose_name='Секция Объекта')),
                ('window_view', models.ManyToManyField(to='realty.ObjectSiteWindowsView', verbose_name='Вид из окон')),
            ],
            options={
                'verbose_name': 'Помещение',
                'verbose_name_plural': 'Помещения (квартиры, апартаменты, коммерческие)',
            },
        ),
        migrations.AddField(
            model_name='objectsection',
            name='object',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='realty.Object', verbose_name='Объект'),
        ),
        migrations.AddField(
            model_name='objectsection',
            name='object_block',
            field=models.ForeignKey(blank=True, default=0, null=True, on_delete=django.db.models.deletion.CASCADE, to='realty.ObjectBlock', verbose_name='Блок Объекта'),
        ),
        migrations.CreateModel(
            name='ObjectInfoTab',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.PositiveIntegerField(blank=True, default=0, help_text='Чем выше число, тем ниже объект в списке', null=True, verbose_name='Порядок')),
                ('icon_name', models.SlugField(blank=True, choices=[('about', 'Об объекте'), ('architecture', 'Архитектура'), ('land-improvement', 'Благоустройство'), ('location', 'Расположение'), ('communications', 'Коммуникации'), ('arrangement', 'Планировки'), ('storage-room', 'Кладовые')], max_length=100, null=True, verbose_name='Имя иконки')),
                ('description', ckeditor.fields.RichTextField(blank=True, null=True, verbose_name='Описание')),
                ('image', models.ImageField(blank=True, null=True, upload_to=apps.realty.models.object_info_tab.image_upload_path, verbose_name='Изображение')),
                ('object', models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='realty.Object')),
            ],
            options={
                'verbose_name': 'Таб [Информация об объекте]',
                'verbose_name_plural': 'Табы [Информация об объекте: Об объекте, Архитектура, Благоустройство, Расположение, Коммуникации, Планировки, Кладовые...]',
            },
        ),
        migrations.CreateModel(
            name='ObjectGalleryImage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to=apps.realty.models.object_gallery.image_upload_path, verbose_name='Изображение')),
                ('gallery', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='realty.ObjectGallery', verbose_name='Галерея')),
            ],
            options={
                'verbose_name': 'Изображение',
                'verbose_name_plural': 'Изображения',
            },
        ),
        migrations.AddField(
            model_name='objectgallery',
            name='object',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='realty.Object', verbose_name='Объект'),
        ),
        migrations.CreateModel(
            name='ObjectFile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, choices=[('info_booklet', 'Информационный буклет'), ('object_genplan', 'Генплан объекта недвижимости'), ('commercial_offer', 'Коммерческое предложение')], max_length=100, null=True, verbose_name='Название документа')),
                ('file', models.FileField(blank=True, null=True, upload_to=apps.realty.models.object_file.file_upload_path, verbose_name='Файл')),
                ('object', models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='realty.Object')),
            ],
            options={
                'verbose_name': 'Фаил Объекта',
                'verbose_name_plural': 'Файлы Объектов [Информационный буклет, Генплан объекта недвижимости, Коммерческое предложение]',
            },
        ),
        migrations.CreateModel(
            name='ObjectElevator',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('elevator_type', models.CharField(blank=True, choices=[('passenger_lift', 'Пассажирский лифт'), ('cargo_lift', 'Грузовой лифт')], max_length=100, null=True, verbose_name='Тип лифта')),
                ('elevator_qty', models.PositiveIntegerField(blank=True, default=1, null=True, verbose_name='Количество лифтов')),
                ('object_section', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='realty.ObjectSection', verbose_name='Секция Объекта')),
            ],
            options={
                'verbose_name': 'Лифт Объекта',
                'verbose_name_plural': 'Лифты Объекта',
            },
        ),
        migrations.CreateModel(
            name='ObjectDocument',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=255, null=True, verbose_name='Название документа')),
                ('date', models.DateField(default=datetime.date.today, verbose_name='Дата')),
                ('file', models.FileField(blank=True, null=True, upload_to=apps.realty.models.object_document.file_upload_path, verbose_name='Файл')),
                ('updated', models.DateTimeField(auto_now=True, null=True)),
                ('author', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='realty.ObjectDocumentAuthor', verbose_name='Автор')),
                ('object', models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='realty.Object')),
            ],
            options={
                'verbose_name': 'Документ',
                'verbose_name_plural': 'Документы',
            },
        ),
        migrations.AddField(
            model_name='objectblock',
            name='object',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='realty.Object', verbose_name='Объект'),
        ),
        migrations.CreateModel(
            name='ObjectBathroom',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bathroom_type', models.CharField(blank=True, choices=[('0', 'Совмещенный'), ('1', 'Раздельный')], max_length=100, null=True, verbose_name='Тип санузла')),
                ('bathroom_qty', models.PositiveIntegerField(blank=True, default=1, null=True, verbose_name='Количество санузлов')),
                ('object_site', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='realty.ObjectSite')),
            ],
            options={
                'verbose_name': 'Санузел',
                'verbose_name_plural': 'Санузлы',
            },
        ),
        migrations.CreateModel(
            name='ObjectBalcony',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('balcony_type', models.CharField(blank=True, choices=[('balcony', 'Балкон'), ('loggia', 'Лоджия'), ('terrace', 'Терраса'), ('patio', 'Патио'), ('french_balcony', 'Французский балкон'), ('bay_window', 'Эркер')], max_length=100, null=True, verbose_name='Тип балкона')),
                ('balcony_qty', models.PositiveIntegerField(blank=True, default=1, null=True, verbose_name='Количество балконов')),
                ('object_site', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='realty.ObjectSite')),
            ],
            options={
                'verbose_name': 'Балкон',
                'verbose_name_plural': 'Балконы в помещении',
            },
        ),
        migrations.AddField(
            model_name='object',
            name='category',
            field=models.ManyToManyField(help_text='Выберите категорию(и) объекта недвижимости', to='realty.ObjectCategory', verbose_name='Категория объекта'),
        ),
    ]
