# Generated by Django 3.0 on 2019-12-10 09:53

import apps.realty.models.object
from django.db import migrations
import imagekit.models.fields


class Migration(migrations.Migration):

    dependencies = [
        ('realty', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='object',
            name='slider_completed_image',
            field=imagekit.models.fields.ProcessedImageField(blank=True, null=True, upload_to=apps.realty.models.object.slider_image_upload, verbose_name='Изображение для слайдера Завершенный объект'),
        ),
        migrations.AlterField(
            model_name='object',
            name='slider_main_image',
            field=imagekit.models.fields.ProcessedImageField(blank=True, null=True, upload_to=apps.realty.models.object.slider_image_upload, verbose_name='Изображение для слайдера на Главной'),
        ),
    ]
