# Generated by Django 3.0 on 2019-12-05 08:59

import apps.realty.models.object_commercial_info_tab
import ckeditor.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('realty', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='objectinfotab',
            options={'verbose_name': 'Таб [Информация об объекте]', 'verbose_name_plural': 'Табы [Информация об объектах]'},
        ),
        migrations.CreateModel(
            name='ObjectCommercialInfoTab',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('icon_name', models.SlugField(blank=True, choices=[('about', 'Об объекте'), ('architecture', 'Архитектура'), ('land-improvement', 'Благоустройство'), ('location', 'Расположение'), ('communications', 'Коммуникации'), ('arrangement', 'Планировки'), ('storage-room', 'Кладовые'), ('parking', 'Паркинг'), ('servicing', 'Обслуживание')], max_length=100, null=True, verbose_name='Имя иконки (оно же заголовок таба)')),
                ('description', ckeditor.fields.RichTextField(blank=True, null=True, verbose_name='Описание')),
                ('image', models.ImageField(blank=True, null=True, upload_to=apps.realty.models.object_commercial_info_tab.image_upload_path, verbose_name='Изображение')),
                ('object_commercial', models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='realty.ObjectCommercial')),
            ],
            options={
                'verbose_name': 'Таб [Информация о коммерческом объекте]',
                'verbose_name_plural': 'Табы [Информация об коммерческих объектах]',
            },
        ),
    ]
