# Generated by Django 2.2 on 2019-04-08 14:38

import ckeditor.fields
from django.db import migrations, models
import django.db.models.deletion
import location_field.models.plain
import multiselectfield.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('realty', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='object',
            options={'verbose_name': 'Объект', 'verbose_name_plural': 'Объекты (Жилые, Коммерческие)'},
        ),
        migrations.AddField(
            model_name='object',
            name='address',
            field=models.CharField(blank=True, help_text='Город, улица, номер дома (для завершенных/построенных объектов)', max_length=255, null=True, verbose_name='Адрес'),
        ),
        migrations.AddField(
            model_name='object',
            name='category',
            field=multiselectfield.db.fields.MultiSelectField(choices=[('living', 'Жилой'), ('commercial', 'Коммерческий')], default=['living', 'commercial'], help_text='Выберите категорию(и) объекта недвижимости', max_length=17, verbose_name='Категория объекта'),
        ),
        migrations.AddField(
            model_name='object',
            name='city',
            field=models.CharField(choices=[('alushta', 'Алушта'), ('evpatoriya', 'Евпатория'), ('simferopol', 'Симферополь'), ('yalta', 'Ялта')], default=0, max_length=100, verbose_name='Город'),
        ),
        migrations.AddField(
            model_name='object',
            name='created',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='object',
            name='crm_id',
            field=models.CharField(blank=True, help_text='ID объекта в 1C (Заполняется автоматически при выгрузке)', max_length=100, null=True, verbose_name='CRM ID'),
        ),
        migrations.AddField(
            model_name='object',
            name='description',
            field=ckeditor.fields.RichTextField(blank=True, null=True, verbose_name='Описание'),
        ),
        migrations.AddField(
            model_name='object',
            name='has_military',
            field=models.BooleanField(default=False, help_text='Подходит ли данный объект для военной ипотеки', verbose_name='Военная ипотека'),
        ),
        migrations.AddField(
            model_name='object',
            name='location',
            field=location_field.models.plain.PlainLocationField(blank=True, max_length=63, null=True, verbose_name='Локация'),
        ),
        migrations.AddField(
            model_name='object',
            name='object_type',
            field=models.CharField(choices=[('business_center', 'Бизнес центр'), ('city', 'Город'), ('living_house', 'Жилой дом'), ('living_quarter', 'Жилой квартал'), ('living_complex', 'Жилой комплекс'), ('resort_complex', 'Курортный комплекс'), ('multipurposes_complex', 'Многофункциональный комплекс'), ('family_quarter', 'Семейный квартал'), ('business_and_retail_center', 'Торгово-офисный центр'), ('mall', 'Торговый центр')], default=0, max_length=100, verbose_name='Тип Объекта'),
        ),
        migrations.AddField(
            model_name='object',
            name='order',
            field=models.PositiveIntegerField(blank=True, default=0, help_text='Чем выше число, тем ниже объект в списке', null=True, verbose_name='Порядок'),
        ),
        migrations.AddField(
            model_name='object',
            name='panoram',
            field=models.URLField(blank=True, help_text='e.g.: https://monolit360.com/files/main/index.html?s=pano1692', null=True, verbose_name='Cсылка на панораму'),
        ),
        migrations.AddField(
            model_name='object',
            name='updated',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
        migrations.AddField(
            model_name='object',
            name='webcam',
            field=models.URLField(blank=True, help_text='e.g.: https://rtsp.me/embed/3KASrTkG/', null=True, verbose_name='Cсылка на web-камеру'),
        ),
        migrations.AlterField(
            model_name='object',
            name='active',
            field=models.BooleanField(default=True, help_text='Опубликован на сайте', verbose_name='Активный'),
        ),
        migrations.AlterField(
            model_name='object',
            name='completed',
            field=models.BooleanField(default=False, verbose_name='Строительство завершено'),
        ),
        migrations.AlterField(
            model_name='object',
            name='slug',
            field=models.SlugField(help_text='e.g.: status-house (max 100 chars), получим https://monolit.site/objects/status-house/', max_length=100, verbose_name='URL адрес'),
        ),
        migrations.CreateModel(
            name='ObjectInfoTab',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Название Вкладки')),
                ('icon_name', models.SlugField(blank=True, help_text='e.g.: object-about', max_length=100, null=True, verbose_name='Имя иконки')),
                ('description', ckeditor.fields.RichTextField(blank=True, null=True, verbose_name='Описание')),
                ('image', models.ImageField(blank=True, null=True, upload_to='images/objects/info_tabs/', verbose_name='Изображение')),
                ('object', models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='realty.Object')),
            ],
            options={
                'verbose_name': 'Таб [Информация об объекте]',
                'verbose_name_plural': 'Табы [Информация об объекте]',
            },
        ),
    ]
