# Generated by Django 2.2.1 on 2019-05-22 07:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('realty', '0002_auto_20190522_1038'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='objectinfotab',
            name='order',
        ),
        migrations.AlterField(
            model_name='objectinfotab',
            name='icon_name',
            field=models.SlugField(blank=True, choices=[('about', 'Об объекте'), ('architecture', 'Архитектура'), ('land-improvement', 'Благоустройство'), ('location', 'Расположение'), ('communications', 'Коммуникации'), ('arrangement', 'Планировки'), ('storage-room', 'Кладовые'), ('parking', 'Паркинг')], max_length=100, null=True, verbose_name='Имя иконки (оно же заголовок таба)'),
        ),
    ]
