# Generated by Django 2.2.3 on 2019-07-31 10:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('realty', '0002_auto_20190731_1114'),
    ]

    operations = [
        migrations.AlterField(
            model_name='objectsite',
            name='object',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='realty.Object', verbose_name='Объект'),
            preserve_default=False,
        ),
    ]
