# Generated by Django 2.2 on 2019-04-16 06:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('realty', '0002_auto_20190415_1744'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='image',
            name='title',
        ),
    ]
