# Generated by Django 2.2.1 on 2019-05-15 13:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('realty', '0002_auto_20190514_1730'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='objectinfotab',
            options={'verbose_name': 'Таб [Информация об объекте]', 'verbose_name_plural': 'Табы [Информация об объекте: Об объекте, Архитектура, Благоустройство, Расположение, Коммуникации, Планировки, Кладовые...]'},
        ),
        migrations.AlterField(
            model_name='objectinfotab',
            name='icon_name',
            field=models.SlugField(blank=True, choices=[('about', 'Об объекте'), ('architecture', 'Архитектура'), ('land-improvement', 'Благоустройство'), ('location', 'Расположение'), ('communications', 'Коммуникации'), ('arrangement', 'Планировки'), ('storage-room', 'Кладовые')], max_length=100, null=True, verbose_name='Имя иконки'),
        ),
    ]
