# Generated by Django 3.0.2 on 2020-01-13 09:36

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('realty', '0002_auto_20191210_1253'),
    ]

    operations = [
        migrations.AlterField(
            model_name='objectsection',
            name='comlete_year',
            field=models.PositiveIntegerField(blank=True, default=2020, help_text='Допустимые значения от 2006 до 2100', null=True, validators=[django.core.validators.MinValueValidator(2006), django.core.validators.MaxValueValidator(2100)], verbose_name='Год сдачи'),
        ),
    ]
