# Generated by Django 2.2.4 on 2019-09-02 08:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('realty', '0002_auto_20190826_1920'),
    ]

    operations = [
        migrations.AddField(
            model_name='object',
            name='partnership',
            field=models.BooleanField(default=False, help_text='Участвует ли данный объект в партнерской программе?', verbose_name='Партнерская программа'),
        ),
    ]
