# Generated by Django 2.2.6 on 2019-10-25 14:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('realty', '0002_auto_20191025_1721'),
    ]

    operations = [
        migrations.AddField(
            model_name='objectblock',
            name='object_commercial',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='realty.ObjectCommercial', verbose_name='Коммерческий Объект'),
        ),
        migrations.AlterField(
            model_name='objectblock',
            name='object',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='realty.Object', verbose_name='Жилой Объект'),
        ),
    ]
