# Generated by Django 2.2 on 2019-04-10 07:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('realty', '0002_auto_20190409_1752'),
    ]

    operations = [
        migrations.CreateModel(
            name='ObjectBlock',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=255, null=True, verbose_name='Номер блока или его название')),
                ('object', models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='realty.Object')),
            ],
            options={
                'verbose_name': 'Блок Объекта',
                'verbose_name_plural': 'Объект Блоки',
            },
        ),
        migrations.CreateModel(
            name='ObjectSection',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=255, null=True, verbose_name='Номер секции или её название')),
                ('object', models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='realty.Object')),
                ('object_block', models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='realty.ObjectBlock')),
            ],
            options={
                'verbose_name': 'Секция Объекта',
                'verbose_name_plural': 'Объект Секции',
            },
        ),
    ]
