# Generated by Django 2.2 on 2019-04-12 07:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('realty', '0002_auto_20190412_1041'),
    ]

    operations = [
        migrations.AddField(
            model_name='gallery',
            name='created',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='gallery',
            name='updated',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
    ]
