# Generated by Django 2.2.1 on 2019-05-21 10:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('realty', '0002_auto_20190521_1251'),
    ]

    operations = [
        migrations.AlterField(
            model_name='objectdocument',
            name='author',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='realty.ObjectDocumentAuthor'),
        ),
        migrations.AlterField(
            model_name='objectdocumentauthor',
            name='name',
            field=models.CharField(blank=True, help_text='Пример: Иванов В.А.', max_length=255, null=True, verbose_name='Имя автора'),
        ),
    ]
