# Generated by Django 2.2.3 on 2019-07-04 12:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('realty', '0002_auto_20190703_1028'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='object',
            name='has_military',
        ),
        migrations.RemoveField(
            model_name='object',
            name='has_mother',
        ),
    ]
