# Generated by Django 2.2.4 on 2019-08-26 12:49

import apps.realty.models.object_parking
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('realty', '0002_auto_20190731_1555'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='objectsite',
            options={'verbose_name': 'Жилое помещение', 'verbose_name_plural': 'Помещения жилые (Квартиры и Апартаменты)'},
        ),
        migrations.AlterField(
            model_name='objectsite',
            name='site_type',
            field=models.CharField(choices=[('flat', 'Квартира'), ('apartments', 'Апартаменты')], max_length=100, verbose_name='Тип помещения'),
        ),
        migrations.CreateModel(
            name='ObjectParking',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('site_number', models.CharField(blank=True, max_length=100, null=True, verbose_name='Номер помещения')),
                ('site_area', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True, verbose_name='Площадь помещения')),
                ('price_per_square', models.DecimalField(blank=True, decimal_places=2, help_text='Стоимость одного квадратного метра', max_digits=8, null=True, verbose_name='Цена за м2 (руб.)')),
                ('price_total', models.DecimalField(blank=True, decimal_places=2, help_text='Считается автоматически из Площади помещения * Цена за м2', max_digits=11, null=True, verbose_name='Общая стоимость (руб.)')),
                ('image_planning', models.ImageField(blank=True, null=True, upload_to=apps.realty.models.object_parking.image_upload_path, verbose_name='Планировка')),
                ('image_planning_parking', models.ImageField(blank=True, null=True, upload_to=apps.realty.models.object_parking.image_upload_path, verbose_name='Место на плане паркинга')),
                ('object_section', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='realty.ObjectSection', verbose_name='Секция Объекта')),
            ],
            options={
                'verbose_name': 'Парковочное место',
                'verbose_name_plural': 'Парковочные места',
            },
        ),
    ]
