# Generated by Django 2.2 on 2019-04-25 13:51

import apps.realty.models.object_info_tab
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('realty', '0002_auto_20190425_1547'),
    ]

    operations = [
        migrations.AlterField(
            model_name='objectinfotab',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=apps.realty.models.object_info_tab.image_upload_path, verbose_name='Изображение'),
        ),
    ]
