# Generated by Django 2.2.3 on 2019-07-10 12:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('realty', '0002_auto_20190710_0957'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='object',
            name='mortgage_military',
        ),
        migrations.RemoveField(
            model_name='object',
            name='mortgage_mother',
        ),
    ]
