# Generated by Django 2.2 on 2019-04-10 09:56

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('realty', '0002_auto_20190410_1133'),
    ]

    operations = [
        migrations.AddField(
            model_name='objectsection',
            name='year_finish',
            field=models.PositiveIntegerField(default=2019, validators=[django.core.validators.MinValueValidator(2019), django.core.validators.MaxValueValidator(2100)], verbose_name='Год'),
        ),
    ]
