# Generated by Django 2.2 on 2019-04-08 15:52

from django.db import migrations, models
import location_field.models.plain
import multiselectfield.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('realty', '0002_auto_20190408_1738'),
    ]

    operations = [
        migrations.AlterField(
            model_name='object',
            name='category',
            field=multiselectfield.db.fields.MultiSelectField(blank=True, choices=[('living', 'Жилой'), ('commercial', 'Коммерческий')], help_text='Выберите категорию(и) объекта недвижимости', max_length=17, null=True, verbose_name='Категория объекта'),
        ),
        migrations.AlterField(
            model_name='object',
            name='city',
            field=models.CharField(blank=True, choices=[('alushta', 'Алушта'), ('evpatoriya', 'Евпатория'), ('simferopol', 'Симферополь'), ('yalta', 'Ялта')], max_length=100, null=True, verbose_name='Город'),
        ),
        migrations.AlterField(
            model_name='object',
            name='location',
            field=location_field.models.plain.PlainLocationField(blank=True, help_text='Географические координаты - широта и долгота', max_length=63, null=True, verbose_name='Локация'),
        ),
        migrations.AlterField(
            model_name='object',
            name='object_type',
            field=models.CharField(blank=True, choices=[('business_center', 'Бизнес центр'), ('city', 'Город'), ('living_house', 'Жилой дом'), ('living_quarter', 'Жилой квартал'), ('living_complex', 'Жилой комплекс'), ('resort_complex', 'Курортный комплекс'), ('multipurposes_complex', 'Многофункциональный комплекс'), ('family_quarter', 'Семейный квартал'), ('business_and_retail_center', 'Торгово-офисный центр'), ('mall', 'Торговый центр')], max_length=100, null=True, verbose_name='Тип Объекта'),
        ),
    ]
