# Generated by Django 2.2 on 2019-04-05 09:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('realty', '0002_auto_20190405_1048'),
    ]

    operations = [
        migrations.AddField(
            model_name='object',
            name='order',
            field=models.PositiveIntegerField(blank=True, default=0, null=True, verbose_name='Порядок'),
        ),
        migrations.AlterField(
            model_name='object',
            name='object_type',
            field=models.CharField(choices=[('business_center', 'Бизнес центр'), ('city', 'Город'), ('living_house', 'Жилой дом'), ('living_quarter', 'Жилой квартал'), ('living_complex', 'Жилой комплекс'), ('resort_complex', 'Курортный комплекс'), ('multipurposes_complex', 'Многофункциональный комплекс'), ('family_quarter', 'Семейный квартал'), ('business_and_retail_center', 'Торгово-офисный центр'), ('mall', 'Торговый центр')], max_length=100, verbose_name='Тип Объекта'),
        ),
    ]
