# Generated by Django 2.2.6 on 2019-10-30 10:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('realty', '0002_auto_20191030_1337'),
    ]

    operations = [
        migrations.AddField(
            model_name='objectcommercialsite',
            name='ceiling_height',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Пример: 2.30 = 2 метра 30 см', max_digits=4, null=True, verbose_name='Высота потолка (м)'),
        ),
        migrations.AddField(
            model_name='objectcommercialsite',
            name='site_area',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True, verbose_name='Площадь помещения'),
        ),
    ]
