# Generated by Django 2.2.4 on 2019-08-26 13:00

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('realty', '0003_auto_20190826_1549'),
    ]

    operations = [
        migrations.AddField(
            model_name='objectparking',
            name='floor',
            field=models.IntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(-5), django.core.validators.MaxValueValidator(100)], verbose_name='Этаж'),
        ),
    ]
