# Generated by Django 2.2.1 on 2019-05-15 14:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('realty', '0003_auto_20190515_1618'),
    ]

    operations = [
        migrations.AlterField(
            model_name='objectfile',
            name='title',
            field=models.CharField(blank=True, choices=[('info_booklet', 'Информационный буклет'), ('object_genplan', 'Генплан объекта недвижимости'), ('commercial_offer', 'Коммерческое предложение')], max_length=100, null=True, verbose_name='Название документа'),
        ),
    ]
