# Generated by Django 2.2.1 on 2019-05-22 10:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('realty', '0003_auto_20190522_1057'),
    ]

    operations = [
        migrations.AlterField(
            model_name='objectdocument',
            name='title',
            field=models.CharField(max_length=255, verbose_name='Название документа'),
        ),
    ]
