# Generated by Django 2.2 on 2019-04-16 14:17

import apps.realty.models.object_gallery
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('realty', '0003_remove_image_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='image',
            name='image',
            field=models.ImageField(upload_to=apps.realty.models.object_gallery.upload_path, verbose_name='Изображение'),
        ),
    ]
