# Generated by Django 2.2 on 2019-04-12 08:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('realty', '0003_auto_20190412_1058'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='gallery',
            name='created',
        ),
    ]
