# Generated by Django 2.2 on 2019-04-10 10:00

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('realty', '0003_objectsection_year_finish'),
    ]

    operations = [
        migrations.AlterField(
            model_name='objectsection',
            name='year_finish',
            field=models.PositiveIntegerField(blank=True, default='', null=True, validators=[django.core.validators.MinValueValidator(2019), django.core.validators.MaxValueValidator(2100)], verbose_name='Год'),
        ),
    ]
