# Generated by Django 2.2 on 2019-04-05 13:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('realty', '0003_auto_20190405_1256'),
    ]

    operations = [
        migrations.AddField(
            model_name='object',
            name='has_military',
            field=models.BooleanField(default=False, help_text='Подходит ли данный объект для военной ипотеки', verbose_name='Военная ипотеки'),
        ),
        migrations.AlterField(
            model_name='object',
            name='address',
            field=models.CharField(blank=True, help_text='Улица и номер дома', max_length=255, null=True, verbose_name='Адрес'),
        ),
        migrations.AlterField(
            model_name='object',
            name='order',
            field=models.PositiveIntegerField(blank=True, default=0, help_text='Чем выше число, тем ниже объект в списке', null=True, verbose_name='Порядок'),
        ),
        migrations.AlterField(
            model_name='object',
            name='slug',
            field=models.SlugField(help_text='e.g.: status-house (max 100 chars), получим https://monolit.site/objects/status-house/', max_length=100, verbose_name='URL адрес'),
        ),
    ]
