# Generated by Django 2.2.6 on 2019-10-30 12:10

import apps.realty.models.object_commercial
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('realty', '0003_auto_20191030_1346'),
    ]

    operations = [
        migrations.AddField(
            model_name='objectcommercial',
            name='main_image',
            field=models.ImageField(blank=True, null=True, upload_to=apps.realty.models.object_commercial.image_upload_path, verbose_name='Главное изображение'),
        ),
        migrations.AddField(
            model_name='objectcommercialsite',
            name='rooms_qty',
            field=models.CharField(blank=True, choices=[('0', 'Студия'), ('1', '1 комната'), ('2', '2 комнаты')], max_length=100, null=True, verbose_name='Количество комнат в помещении'),
        ),
    ]
