# Generated by Django 2.2 on 2019-04-26 14:19

import apps.realty.models.object_file
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('realty', '0003_auto_20190425_1651'),
    ]

    operations = [
        migrations.AlterField(
            model_name='objectfile',
            name='file',
            field=models.FileField(blank=True, null=True, upload_to=apps.realty.models.object_file.file_upload_path, verbose_name='Файл'),
        ),
    ]
