# Generated by Django 2.2.3 on 2019-07-15 12:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('realty', '0003_auto_20190710_1501'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='objectsite',
            options={'verbose_name': 'Помещение', 'verbose_name_plural': 'Помещения (Квартиры, Апартаменты, Коммерческие помещения)'},
        ),
    ]
