# Generated by Django 2.2 on 2019-04-10 07:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('realty', '0003_objectblock_objectsection'),
    ]

    operations = [
        migrations.AlterField(
            model_name='objectblock',
            name='object',
            field=models.ForeignKey(blank=True, default=0, null=True, on_delete=django.db.models.deletion.CASCADE, to='realty.Object'),
        ),
        migrations.AlterField(
            model_name='objectsection',
            name='object',
            field=models.ForeignKey(blank=True, default=0, null=True, on_delete=django.db.models.deletion.CASCADE, to='realty.Object'),
        ),
        migrations.AlterField(
            model_name='objectsection',
            name='object_block',
            field=models.ForeignKey(blank=True, default=0, null=True, on_delete=django.db.models.deletion.CASCADE, to='realty.ObjectBlock'),
        ),
    ]
