# Generated by Django 2.2.3 on 2019-07-05 07:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('realty', '0003_auto_20190704_1528'),
    ]

    operations = [
        migrations.AlterField(
            model_name='objectsite',
            name='object',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='realty.Object', verbose_name='Объект'),
        ),
    ]
