# Generated by Django 2.2.1 on 2019-06-10 09:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('realty', '0003_auto_20190606_1108'),
    ]

    operations = [
        migrations.RenameField(
            model_name='objectsite',
            old_name='status',
            new_name='active',
        ),
    ]
