# Generated by Django 2.2.4 on 2019-09-04 14:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('realty', '0003_object_partnership'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='objectfile',
            options={'verbose_name': 'Файл Объекта', 'verbose_name_plural': 'Файлы Объектов (Информационный буклет, Генплан объекта недвижимости, Коммерческое предложение)'},
        ),
    ]
