# Generated by Django 2.2.1 on 2019-06-10 13:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('realty', '0004_auto_20190610_1238'),
    ]

    operations = [
        migrations.AlterField(
            model_name='objectsite',
            name='rooms_qty',
            field=models.CharField(blank=True, choices=[('0', 'Студия'), ('1', '1 комнатная'), ('2', '2 комнатная'), ('3', '3 комнатная'), ('4', '4 комнатная'), ('5', '5 комнатная')], max_length=100, null=True, verbose_name='Количество комнат в помещении'),
        ),
        migrations.AlterField(
            model_name='objectsite',
            name='site_type',
            field=models.CharField(choices=[('flat', 'Квартира'), ('apartments', 'Апартаменты'), ('commercial', 'Коммерческое помещение')], max_length=100, verbose_name='Тип помещения'),
        ),
    ]
