# Generated by Django 2.2.1 on 2019-05-15 14:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('realty', '0004_auto_20190515_1714'),
    ]

    operations = [
        migrations.RenameField(
            model_name='objectfile',
            old_name='title',
            new_name='name',
        ),
    ]
