# Generated by Django 2.2.6 on 2019-10-29 06:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('realty', '0004_auto_20191028_1541'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='objectblock',
            options={'verbose_name': 'Блок Объекта', 'verbose_name_plural': 'Объекты (Блоки)'},
        ),
        migrations.AddField(
            model_name='objectcommercial',
            name='city',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='realty.ObjectCities', verbose_name='Город'),
        ),
    ]
