# Generated by Django 2.2.4 on 2019-08-26 13:37

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('realty', '0004_objectparking_floor'),
    ]

    operations = [
        migrations.AddField(
            model_name='objectparking',
            name='crm_id',
            field=models.CharField(default=1, help_text='ID объекта в 1C (Заполняется автоматически при выгрузке)', max_length=100, unique=True, verbose_name='CRM ID'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='objectparking',
            name='floor',
            field=models.IntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(-5), django.core.validators.MaxValueValidator(5)], verbose_name='Этаж'),
        ),
    ]
