# Generated by Django 2.2 on 2019-04-11 15:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('realty', '0004_remove_gallery_object'),
    ]

    operations = [
        migrations.AddField(
            model_name='object',
            name='galleries',
            field=models.ManyToManyField(help_text='Связанные с Объектом галереи изображений', to='realty.Gallery', verbose_name='Галереи Объекта'),
        ),
    ]
