# Generated by Django 2.2.3 on 2019-07-25 06:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('realty', '0004_auto_20190715_1537'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='objectfile',
            options={'verbose_name': 'Файл Объекта', 'verbose_name_plural': 'Файлы Объектов [Информационный буклет, Генплан объекта недвижимости, Коммерческое предложение]'},
        ),
        migrations.AlterField(
            model_name='objectdocumentauthor',
            name='name',
            field=models.CharField(help_text='Пример: Иванов В.А.', max_length=255, unique=True, verbose_name='Автор'),
        ),
    ]
