# Generated by Django 2.2 on 2019-04-16 14:52

import apps.realty.models.object_gallery
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('realty', '0004_auto_20190416_1717'),
    ]

    operations = [
        migrations.AlterField(
            model_name='image',
            name='image',
            field=models.ImageField(null=True, upload_to=apps.realty.models.object_gallery.upload_path, verbose_name='Изображение'),
        ),
    ]
