# Generated by Django 2.2.6 on 2019-10-30 12:30

import apps.realty.models.object_commercial
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('realty', '0004_auto_20191030_1510'),
    ]

    operations = [
        migrations.AddField(
            model_name='objectcommercial',
            name='genplan',
            field=models.ImageField(blank=True, help_text='Изображение с генпланом', null=True, upload_to=apps.realty.models.object_commercial.genplan_upload_path, verbose_name='Генплан'),
        ),
    ]
