# Generated by Django 2.2 on 2019-04-12 08:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('realty', '0004_remove_gallery_created'),
    ]

    operations = [
        migrations.AddField(
            model_name='object',
            name='building_type',
            field=models.CharField(blank=True, choices=[('monolith', 'Монолитный'), ('monolith_frame', 'Монолитно-каркасный'), ('panel', 'Панельный')], max_length=100, null=True, verbose_name='Тип Здания'),
        ),
    ]
