# Generated by Django 2.2.1 on 2019-05-28 05:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('realty', '0004_auto_20190522_1346'),
    ]

    operations = [
        migrations.AddField(
            model_name='object',
            name='genplan_svg',
            field=models.TextField(blank=True, null=True, verbose_name='SVG Генплан'),
        ),
    ]
