# Generated by Django 2.2 on 2019-04-10 07:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('realty', '0004_auto_20190410_1030'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='objectsection',
            options={'verbose_name': 'Секция Объекта', 'verbose_name_plural': 'Объекты (Секции)'},
        ),
        migrations.AlterField(
            model_name='objectsection',
            name='name',
            field=models.CharField(max_length=255, verbose_name='Номер секции или её название'),
        ),
        migrations.AlterField(
            model_name='objectsection',
            name='object',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='realty.Object'),
        ),
        migrations.AlterField(
            model_name='objectsection',
            name='object_block',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='realty.ObjectBlock'),
        ),
    ]
