# Generated by Django 2.2 on 2019-04-05 14:17

from django.db import migrations, models
import django.utils.timezone
import location_field.models.plain


class Migration(migrations.Migration):

    dependencies = [
        ('realty', '0004_auto_20190405_1644'),
    ]

    operations = [
        migrations.AddField(
            model_name='object',
            name='location',
            field=location_field.models.plain.PlainLocationField(default=django.utils.timezone.now, max_length=63),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='object',
            name='address',
            field=models.CharField(blank=True, help_text='Город, улица, номер дома (для завершенных/построенных объектов)', max_length=255, null=True, verbose_name='Адрес'),
        ),
        migrations.AlterField(
            model_name='object',
            name='has_military',
            field=models.BooleanField(default=False, help_text='Подходит ли данный объект для военной ипотеки', verbose_name='Военная ипотека'),
        ),
    ]
