# Generated by Django 2.2 on 2019-04-10 14:23

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('realty', '0004_auto_20190410_1300'),
    ]

    operations = [
        migrations.AlterField(
            model_name='objectblock',
            name='object',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='realty.Object'),
        ),
        migrations.AlterField(
            model_name='objectsection',
            name='year_finish',
            field=models.PositiveIntegerField(blank=True, default='', help_text='Допустимые значения от 2019 до 2100', null=True, validators=[django.core.validators.MinValueValidator(2019), django.core.validators.MaxValueValidator(2100)], verbose_name='Год сдачи'),
        ),
    ]
