# Generated by Django 2.2 on 2019-04-10 14:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('realty', '0005_auto_20190410_1723'),
    ]

    operations = [
        migrations.AlterField(
            model_name='objectsection',
            name='name',
            field=models.CharField(max_length=255, verbose_name='Номер секции или её название'),
        ),
    ]
