# Generated by Django 2.2 on 2019-04-12 09:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('realty', '0005_object_building_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='ObjectSite',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Название помещения')),
                ('crm_id', models.CharField(blank=True, help_text='ID объекта в 1C (Заполняется автоматически при выгрузке)', max_length=100, null=True, verbose_name='CRM ID')),
                ('object', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='realty.Object', verbose_name='Объект')),
            ],
            options={
                'verbose_name': 'Помещение',
                'verbose_name_plural': 'Объекты (Помещения: )',
            },
        ),
    ]
