# Generated by Django 2.2.1 on 2019-05-16 13:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('realty', '0005_auto_20190515_1716'),
    ]

    operations = [
        migrations.RenameField(
            model_name='objectgallery',
            old_name='title',
            new_name='name',
        ),
    ]
