# Generated by Django 2.2 on 2019-04-10 07:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('realty', '0005_auto_20190410_1035'),
    ]

    operations = [
        migrations.AlterField(
            model_name='objectsection',
            name='name',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Номер секции или её название'),
        ),
        migrations.AlterField(
            model_name='objectsection',
            name='object_block',
            field=models.ForeignKey(blank=True, default=0, null=True, on_delete=django.db.models.deletion.CASCADE, to='realty.ObjectBlock'),
        ),
    ]
