# Generated by Django 2.2 on 2019-04-26 15:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('realty', '0005_auto_20190426_1751'),
    ]

    operations = [
        migrations.AlterField(
            model_name='objectsite',
            name='object',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='realty.Object', verbose_name='Объект'),
        ),
    ]
