# Generated by Django 2.2.1 on 2019-06-11 10:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('realty', '0005_auto_20190610_1658'),
    ]

    operations = [
        migrations.AlterField(
            model_name='objectsite',
            name='window_view',
            field=models.ManyToManyField(blank=True, null=True, to='realty.ObjectSiteWindowsView', verbose_name='Вид из окон'),
        ),
    ]
