# Generated by Django 2.2.6 on 2019-10-29 06:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('realty', '0005_auto_20191029_0936'),
    ]

    operations = [
        migrations.AddField(
            model_name='objectsection',
            name='object_commercial',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='realty.ObjectCommercial', verbose_name='Коммерческий Объект'),
        ),
    ]
