# Generated by Django 2.2.6 on 2019-10-30 12:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('realty', '0005_objectcommercial_genplan'),
    ]

    operations = [
        migrations.AddField(
            model_name='objectcommercial',
            name='genplan_svg',
            field=models.TextField(blank=True, null=True, verbose_name='SVG объекты на генплане'),
        ),
        migrations.AddField(
            model_name='objectcommercial',
            name='panoram',
            field=models.URLField(blank=True, help_text='e.g.: https://monolit360.com/files/main/index.html?s=pano1692', null=True, verbose_name='Cсылка на панораму'),
        ),
        migrations.AddField(
            model_name='objectcommercial',
            name='webcam',
            field=models.URLField(blank=True, help_text='e.g.: https://rtsp.me/embed/3KASrTkG/', null=True, verbose_name='Cсылка на web-камеру'),
        ),
    ]
