# Generated by Django 2.2 on 2019-04-10 07:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('realty', '0006_auto_20190410_1041'),
    ]

    operations = [
        migrations.AlterField(
            model_name='objectblock',
            name='object',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='realty.Object'),
        ),
    ]
