# Generated by Django 2.2.6 on 2019-10-29 06:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('realty', '0006_objectsection_object_commercial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='objectsection',
            name='object',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='realty.Object', verbose_name='Жилой Объект'),
        ),
    ]
