# Generated by Django 2.2 on 2019-04-26 15:57

import apps.realty.models.object_site
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('realty', '0006_auto_20190426_1828'),
    ]

    operations = [
        migrations.AlterField(
            model_name='objectsite',
            name='image_floor',
            field=models.ImageField(blank=True, help_text='Планировка квартиры на этаже', null=True, upload_to=apps.realty.models.object_site.image_upload_path, verbose_name='Квартира на этаже'),
        ),
        migrations.AlterField(
            model_name='objectsite',
            name='image_genplan',
            field=models.ImageField(blank=True, help_text='Выделенный дом на генплане', null=True, upload_to=apps.realty.models.object_site.image_upload_path, verbose_name='Дом на генплане'),
        ),
        migrations.AlterField(
            model_name='objectsite',
            name='image_planning',
            field=models.ImageField(blank=True, null=True, upload_to=apps.realty.models.object_site.image_upload_path, verbose_name='Планировка'),
        ),
        migrations.AlterField(
            model_name='objectsite',
            name='image_planning3d',
            field=models.ImageField(blank=True, null=True, upload_to=apps.realty.models.object_site.image_upload_path, verbose_name='Планировка 3D'),
        ),
        migrations.AlterField(
            model_name='objectsite',
            name='image_section',
            field=models.ImageField(blank=True, help_text='Выделенный этаж в секции объекта', null=True, upload_to=apps.realty.models.object_site.image_upload_path, verbose_name='Этаж в секции'),
        ),
        migrations.AlterField(
            model_name='objectsite',
            name='image_section_in_object',
            field=models.ImageField(blank=True, help_text='Выделенная секция в доме', null=True, upload_to=apps.realty.models.object_site.image_upload_path, verbose_name='Секция в доме'),
        ),
        migrations.AlterField(
            model_name='objectsite',
            name='site_type',
            field=models.CharField(blank=True, choices=[('flat', 'Квартира'), ('apartments', 'Апартаменты'), ('commercial', 'Коммерческое помещение')], max_length=100, null=True, verbose_name='Тип помещения'),
        ),
    ]
