# Generated by Django 2.2.1 on 2019-05-30 12:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('realty', '0006_remove_objectvideo_created'),
    ]

    operations = [
        migrations.AlterField(
            model_name='objectvideo',
            name='video_url',
            field=models.CharField(blank=True, help_text='e.g.: https://youtu.be/JbacFR_B-jw', max_length=255, null=True, verbose_name='Cсылка на видео в YouTube'),
        ),
    ]
