# Generated by Django 2.2.1 on 2019-06-13 14:37

from django.db import migrations, models
import location_field.models.plain


class Migration(migrations.Migration):

    dependencies = [
        ('realty', '0006_auto_20190611_1308'),
    ]

    operations = [
        migrations.RenameField(
            model_name='objectsection',
            old_name='floor_start',
            new_name='floor_first',
        ),
        migrations.RenameField(
            model_name='objectsection',
            old_name='floor_end',
            new_name='floor_last',
        ),
        migrations.AlterField(
            model_name='object',
            name='location',
            field=location_field.models.plain.PlainLocationField(blank=True, default='44.952117,34.10241700000006', help_text='Географические координаты: широта, долгота', max_length=63, null=True, verbose_name='Локация'),
        ),
        migrations.AlterField(
            model_name='objectsite',
            name='ceiling_height',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Пример: 2.30 = 2 метра 30 см', max_digits=10, null=True, verbose_name='Высота потолка (м)'),
        ),
        migrations.AlterField(
            model_name='objectsite',
            name='window_view',
            field=models.ManyToManyField(blank=True, to='realty.ObjectSiteWindowsView', verbose_name='Вид из окон'),
        ),
    ]
