# Generated by Django 2.2 on 2019-04-12 13:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('realty', '0006_objectsite'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='objectsite',
            options={'verbose_name': 'Помещение', 'verbose_name_plural': 'Помещения (квартиры, апартаменты, коммерческие)'},
        ),
        migrations.AddField(
            model_name='objectsite',
            name='status',
            field=models.BooleanField(default=True, help_text='Опубликован на сайте', verbose_name='Активный'),
        ),
    ]
