# Generated by Django 2.2.6 on 2019-10-30 14:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('realty', '0006_auto_20191030_1552'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='objectcommercialsite',
            name='rooms_qty',
        ),
        migrations.AlterField(
            model_name='objectsite',
            name='kitchen_area',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Пример: 12.7 м2', max_digits=5, null=True, verbose_name='Площадь кухни'),
        ),
        migrations.AlterField(
            model_name='objectsite',
            name='living_area',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Пример: 42 м2', max_digits=6, null=True, verbose_name='Жилая площадь'),
        ),
        migrations.AlterField(
            model_name='objectsite',
            name='site_area',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Пример: 65.5 м2', max_digits=6, null=True, verbose_name='Площадь помещения (в м2)'),
        ),
    ]
