# Generated by Django 2.2.1 on 2019-05-17 08:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('realty', '0006_auto_20190516_1626'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='objectgalleryimage',
            name='alt',
        ),
    ]
