# Generated by Django 2.2 on 2019-04-12 13:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('realty', '0007_auto_20190412_1600'),
    ]

    operations = [
        migrations.AddField(
            model_name='objectsite',
            name='floor',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Этаж'),
        ),
        migrations.AddField(
            model_name='objectsite',
            name='number',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Номер квартиры или помещения'),
        ),
    ]
