# Generated by Django 2.2.6 on 2019-10-30 14:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('realty', '0007_auto_20191030_1721'),
    ]

    operations = [
        migrations.AlterField(
            model_name='objectsite',
            name='kitchen_area',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Пример: 12.7 м2', max_digits=5, null=True, verbose_name='Площадь кухни м2'),
        ),
        migrations.AlterField(
            model_name='objectsite',
            name='living_area',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Пример: 42 м2', max_digits=6, null=True, verbose_name='Жилая площадь м2'),
        ),
        migrations.AlterField(
            model_name='objectsite',
            name='price_per_square',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Стоимость одного квадратного метра', max_digits=8, null=True, verbose_name='Цена за м2 (руб)'),
        ),
        migrations.AlterField(
            model_name='objectsite',
            name='price_total',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Считается автоматически из Площади помещения * Цена за м2', max_digits=11, null=True, verbose_name='Общая стоимость (руб)'),
        ),
        migrations.AlterField(
            model_name='objectsite',
            name='site_area',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Пример: 65.5 м2', max_digits=6, null=True, verbose_name='Площадь помещения м2'),
        ),
    ]
