# Generated by Django 2.2 on 2019-04-10 07:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('realty', '0007_auto_20190410_1051'),
    ]

    operations = [
        migrations.AlterField(
            model_name='objectsection',
            name='object_block',
            field=models.ForeignKey(blank=True, default=0, null=True, on_delete=django.db.models.deletion.CASCADE, to='realty.ObjectBlock', verbose_name='Блок Объекта'),
        ),
    ]
