# Generated by Django 2.2.1 on 2019-06-14 09:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('realty', '0007_auto_20190613_1737'),
    ]

    operations = [
        migrations.AlterField(
            model_name='objectsite',
            name='finish_type',
            field=models.CharField(blank=True, choices=[('0', 'Без отделки'), ('1', 'Черновая'), ('2', 'Чистовая')], max_length=100, null=True, verbose_name='Отделка'),
        ),
    ]
