# Generated by Django 2.2.1 on 2019-05-17 09:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('realty', '0007_remove_objectgalleryimage_alt'),
    ]

    operations = [
        migrations.AddField(
            model_name='objectgallery',
            name='order',
            field=models.PositiveIntegerField(blank=True, default=0, help_text='Чем выше число, тем ниже объект в списке', null=True, verbose_name='Порядок'),
        ),
    ]
