# Generated by Django 2.2 on 2019-04-26 16:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('realty', '0007_auto_20190426_1857'),
    ]

    operations = [
        migrations.AlterField(
            model_name='objectsite',
            name='crm_id',
            field=models.CharField(help_text='ID объекта в 1C (Заполняется автоматически при выгрузке)', max_length=100, unique=True, verbose_name='CRM ID'),
        ),
    ]
