# Generated by Django 2.2.6 on 2019-10-29 07:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('realty', '0007_auto_20191029_0951'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='object',
            options={'verbose_name': 'Жилой Объект', 'verbose_name_plural': '1. Объекты (Жилые)'},
        ),
        migrations.AlterModelOptions(
            name='objectblock',
            options={'verbose_name': 'Блок Объекта', 'verbose_name_plural': '3. Объекты (Блоки)'},
        ),
        migrations.AlterModelOptions(
            name='objectcommercial',
            options={'verbose_name': 'Коммерческий Объект', 'verbose_name_plural': '2. Объекты (Коммерческие)'},
        ),
        migrations.AlterModelOptions(
            name='objectgallery',
            options={'verbose_name': 'Галерея Объекта', 'verbose_name_plural': '1.2 Фото Галереи Объектов'},
        ),
        migrations.AlterModelOptions(
            name='objectsection',
            options={'verbose_name': 'Секция Объекта', 'verbose_name_plural': '4. Объекты (Секции)'},
        ),
        migrations.AlterModelOptions(
            name='objectsite',
            options={'verbose_name': 'Жилое помещение', 'verbose_name_plural': '1.1 Помещения (Жилые)'},
        ),
        migrations.AddField(
            model_name='objectgallery',
            name='object_commercial',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='realty.ObjectCommercial', verbose_name='Коммерческий Объект'),
        ),
        migrations.AlterField(
            model_name='objectgallery',
            name='object',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='realty.Object', verbose_name='Жилой Объект'),
        ),
    ]
