# Generated by Django 2.2.6 on 2019-10-30 14:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('realty', '0008_auto_20191030_1722'),
    ]

    operations = [
        migrations.AlterField(
            model_name='objectcommercialsite',
            name='site_area',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Пример: 115.5 м2', max_digits=6, null=True, verbose_name='Площадь помещения м2'),
        ),
    ]
