# Generated by Django 2.2.1 on 2019-06-14 09:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('realty', '0008_auto_20190614_1237'),
    ]

    operations = [
        migrations.AddField(
            model_name='objectsection',
            name='number',
            field=models.PositiveIntegerField(default=1, help_text='Номер секции цифрой', verbose_name='Номер секции'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='objectsection',
            name='name',
            field=models.CharField(help_text='Название секции и её номер. Например: Секция 1', max_length=255, verbose_name='Название секции'),
        ),
    ]
