# Generated by Django 2.2.1 on 2019-05-21 08:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('realty', '0008_objectgallery_order'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='objectdocument',
            name='created',
        ),
    ]
