# Generated by Django 2.2.6 on 2019-10-30 14:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('realty', '0009_auto_20191030_1730'),
    ]

    operations = [
        migrations.AddField(
            model_name='objectcommercialsite',
            name='street_entrance',
            field=models.BooleanField(default=False, verbose_name='Вход с улицы'),
        ),
        migrations.AlterField(
            model_name='objectsite',
            name='rooms_qty',
            field=models.CharField(blank=True, choices=[('0', 'Студия'), ('1', '1 комнатная'), ('2', '2 комнатная'), ('3', '3 комнатная'), ('4', '4 комнатная'), ('5', '5 комнатная')], max_length=100, null=True, verbose_name='Количество комнат'),
        ),
    ]
