# Generated by Django 2.2 on 2019-04-12 13:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('realty', '0009_auto_20190412_1609'),
    ]

    operations = [
        migrations.RenameField(
            model_name='objectsite',
            old_name='number',
            new_name='site_number',
        ),
        migrations.AddField(
            model_name='objectsite',
            name='site_square',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Площадь помещения'),
        ),
    ]
