# Generated by Django 2.2 on 2019-04-12 13:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('realty', '0010_auto_20190412_1614'),
    ]

    operations = [
        migrations.AddField(
            model_name='objectsite',
            name='ste_type',
            field=models.CharField(blank=True, choices=[('flat', 'Квартира'), ('apartments', 'Апартаменты'), ('commercial', 'Коммерческое')], max_length=100, null=True, verbose_name='Тип помещения'),
        ),
    ]
