# Generated by Django 2.2.6 on 2019-10-30 14:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('realty', '0010_auto_20191030_1742'),
    ]

    operations = [
        migrations.AddField(
            model_name='objectbathroom',
            name='object_commercial_site',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='realty.ObjectCommercialSite'),
        ),
        migrations.AlterField(
            model_name='objectbathroom',
            name='bathroom_type',
            field=models.CharField(blank=True, choices=[('0', 'Совмещенный'), ('1', 'Раздельный'), ('2', 'На этаже'), ('3', 'В помещении')], max_length=100, null=True, verbose_name='Тип санузла'),
        ),
    ]
