# Generated by Django 2.2.2 on 2019-07-01 11:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('realty', '0011_object_all_sold'),
    ]

    operations = [
        migrations.AlterField(
            model_name='object',
            name='all_sold',
            field=models.BooleanField(default=False, help_text='Все квартиры и помещения проданы', verbose_name='Все помещения проданы'),
        ),
    ]
