# Generated by Django 2.2 on 2019-04-12 13:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('realty', '0011_objectsite_ste_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='objectsite',
            name='price_per_square',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Цена за 1 м<sup>2</sup>'),
        ),
    ]
