# Generated by Django 2.2 on 2019-04-12 13:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('realty', '0012_objectsite_price_per_square'),
    ]

    operations = [
        migrations.AlterField(
            model_name='objectsite',
            name='price_per_square',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Стоимость одного квадратного метра', max_digits=10, null=True, verbose_name='Цена за м2'),
        ),
    ]
