# Generated by Django 2.2 on 2019-04-12 13:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('realty', '0013_auto_20190412_1633'),
    ]

    operations = [
        migrations.AddField(
            model_name='objectsite',
            name='prce_total',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=30, null=True, verbose_name='Общая стоимость'),
        ),
        migrations.AlterField(
            model_name='objectsite',
            name='price_per_square',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Стоимость одного квадратного метра', max_digits=20, null=True, verbose_name='Цена за м2'),
        ),
    ]
