# Generated by Django 2.2 on 2019-04-12 13:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('realty', '0014_auto_20190412_1638'),
    ]

    operations = [
        migrations.AddField(
            model_name='objectsite',
            name='rooms_qty',
            field=models.CharField(blank=True, choices=[('0', '0'), ('1', '1'), ('2', '2'), ('3', '3'), ('4', '4'), ('5', '5')], max_length=100, null=True, verbose_name='Количество комнат в помещении'),
        ),
        migrations.AddField(
            model_name='objectsite',
            name='special_offer',
            field=models.BooleanField(default=False, verbose_name='Спецпредложение'),
        ),
    ]
