# Generated by Django 2.2 on 2019-04-12 14:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('realty', '0015_auto_20190412_1650'),
    ]

    operations = [
        migrations.RenameField(
            model_name='objectsite',
            old_name='site_square',
            new_name='site_area',
        ),
    ]
