# Generated by Django 2.2 on 2019-04-12 14:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('realty', '0016_auto_20190412_1714'),
    ]

    operations = [
        migrations.RenameField(
            model_name='objectsite',
            old_name='prce_total',
            new_name='price_total',
        ),
    ]
