# Generated by Django 2.2 on 2019-04-12 14:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('realty', '0017_auto_20190412_1716'),
    ]

    operations = [
        migrations.AddField(
            model_name='objectsite',
            name='kitchen_area',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Площадь кухни'),
        ),
        migrations.AddField(
            model_name='objectsite',
            name='living_area',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Жилая площадь'),
        ),
    ]
