# Generated by Django 2.2.4 on 2019-08-27 12:42

import apps.company.models.certificate
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Certificate',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='Название сертификата')),
                ('image', models.ImageField(blank=True, null=True, upload_to=apps.company.models.certificate.image_upload_path, verbose_name='Фото сертификата')),
            ],
            options={
                'verbose_name': 'Сертификат',
                'verbose_name_plural': 'Сертификаты',
            },
        ),
    ]
