# Generated by Django 2.2.5 on 2019-09-18 10:25

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TenderFaq',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.CharField(max_length=255, verbose_name='Вопрос')),
                ('answer', ckeditor.fields.RichTextField(blank=True, null=True, verbose_name='Ответ')),
            ],
            options={
                'verbose_name': 'Вопрос-ответ по Тендерам',
                'verbose_name_plural': 'Тендеры (Вопросы-ответы)',
            },
        ),
    ]
