# Generated by Django 2.2.4 on 2019-08-28 14:35

import apps.company.models.job
import apps.company.models.management
import apps.company.models.responsibility
import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='JobBlock',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=255, null=True, verbose_name='Заголовок')),
                ('body', ckeditor.fields.RichTextField(blank=True, null=True, verbose_name='Описание')),
                ('image', models.ImageField(blank=True, null=True, upload_to=apps.company.models.job.image_upload_path, verbose_name='Изображение')),
                ('order', models.PositiveIntegerField(default=0, help_text='Чем выше число, тем ниже объект в списке', verbose_name='Порядок')),
            ],
            options={
                'verbose_name': 'Блок (Работа в компании)',
                'verbose_name_plural': 'Работа в компании (Блоки)',
            },
        ),
        migrations.CreateModel(
            name='JobVacancy',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Название должности')),
                ('experience', models.CharField(blank=True, help_text='Требования к опыту соискателя', max_length=255, null=True, verbose_name='Опыт')),
                ('duties', ckeditor.fields.RichTextField(blank=True, help_text='Описание должностных обязанностей', null=True, verbose_name='Обязанности')),
                ('requirements', ckeditor.fields.RichTextField(blank=True, null=True, verbose_name='Требования к соискателю')),
                ('terms', ckeditor.fields.RichTextField(blank=True, help_text='Условия работы или преимущества компании', null=True, verbose_name='Условия')),
                ('salary', models.CharField(blank=True, help_text='Например: от 50 000 руб. или по результатам собеседования', max_length=255, null=True, verbose_name='Зарплата')),
                ('contacts', ckeditor.fields.RichTextField(blank=True, help_text='Контактные данные лица связанного с данной вакансией', null=True, verbose_name='Контакты')),
                ('order', models.PositiveIntegerField(default=0, help_text='Чем выше число, тем ниже объект в списке', verbose_name='Порядок')),
            ],
            options={
                'verbose_name': 'Вакансия (Работа в компании)',
                'verbose_name_plural': 'Работа в компании (Вакансии)',
            },
        ),
        migrations.CreateModel(
            name='Management',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, null=True, upload_to=apps.company.models.management.image_upload_path, verbose_name='Фото руководителя')),
                ('surname', models.CharField(max_length=255, verbose_name='Фамилия')),
                ('name', models.CharField(max_length=255, verbose_name='Имя')),
                ('patronymic', models.CharField(blank=True, max_length=255, null=True, verbose_name='Отчество')),
                ('position', models.CharField(max_length=255, verbose_name='Должность')),
                ('order', models.PositiveIntegerField(blank=True, default=0, help_text='Чем выше число, тем ниже объект в списке', null=True, verbose_name='Порядок')),
            ],
            options={
                'verbose_name': 'Менеджмент (Рукововодство)',
                'verbose_name_plural': 'Менеджмент (Руководители)',
            },
        ),
        migrations.CreateModel(
            name='Responsibility',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, null=True, upload_to=apps.company.models.responsibility.image_upload_path, verbose_name='Изображение')),
                ('title', models.CharField(blank=True, max_length=255, null=True, verbose_name='Заголовок')),
                ('body', ckeditor.fields.RichTextField(blank=True, null=True, verbose_name='Описание')),
                ('order', models.PositiveIntegerField(default=0, help_text='Чем выше число, тем ниже объект в списке', verbose_name='Порядок')),
            ],
            options={
                'verbose_name': 'Блок Социальной ответственности',
                'verbose_name_plural': 'Социальная ответственность (Блоки)',
            },
        ),
    ]
