# Generated by Django 3.0.2 on 2020-01-13 09:36

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='history',
            name='year',
            field=models.PositiveIntegerField(default=2020, unique=True, validators=[django.core.validators.MinValueValidator(2005), django.core.validators.MaxValueValidator(2021)], verbose_name='Год'),
        ),
    ]
