# Generated by Django 2.2.4 on 2019-08-30 13:52

import apps.company.models.history
import ckeditor.fields
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0002_jobblock_jobvacancy_management_responsibility'),
    ]

    operations = [
        migrations.CreateModel(
            name='History',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.PositiveIntegerField(default=2019, unique=True, validators=[django.core.validators.MinValueValidator(2005), django.core.validators.MaxValueValidator(2019)], verbose_name='Год')),
                ('body', ckeditor.fields.RichTextField(blank=True, null=True, verbose_name='Описание')),
                ('image', models.ImageField(blank=True, null=True, upload_to=apps.company.models.history.image_upload_path, verbose_name='Изображение')),
            ],
            options={
                'verbose_name': 'Блок (История компании)',
                'verbose_name_plural': 'История компании (Блоки)',
            },
        ),
    ]
