# Generated by Django 2.2.5 on 2019-09-18 11:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0002_tenderfaq'),
    ]

    operations = [
        migrations.AddField(
            model_name='tenderfaq',
            name='active',
            field=models.BooleanField(default=True, help_text='Является ли данный вопрос-ответ активным?', verbose_name='Активный'),
        ),
        migrations.AddField(
            model_name='tenderfaq',
            name='order',
            field=models.PositiveIntegerField(blank=True, default=0, help_text='Чем выше число, тем ниже вопрос в списке', null=True, verbose_name='Порядок'),
        ),
    ]
