# Generated by Django 2.2.4 on 2019-08-30 14:38

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0003_history'),
    ]

    operations = [
        migrations.AlterField(
            model_name='history',
            name='year',
            field=models.PositiveIntegerField(default=2019, unique=True, validators=[django.core.validators.MinValueValidator(2005), django.core.validators.MaxValueValidator(2020)], verbose_name='Год'),
        ),
    ]
