# Generated by Django 2.2.4 on 2019-09-02 07:08

import apps.company.models.structure
import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0004_auto_20190830_1738'),
    ]

    operations = [
        migrations.CreateModel(
            name='Structure',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.URLField(blank=True, max_length=255, null=True, verbose_name='URL сайта')),
                ('body', ckeditor.fields.RichTextField(blank=True, null=True, verbose_name='Описание')),
                ('image', models.ImageField(blank=True, null=True, upload_to=apps.company.models.structure.image_upload_path, verbose_name='Изображение')),
                ('order', models.PositiveIntegerField(default=0, help_text='Чем выше число, тем ниже объект в списке', verbose_name='Порядок')),
            ],
            options={
                'verbose_name': 'Блок (Структура компании)',
                'verbose_name_plural': 'Структура компании (Блоки)',
            },
        ),
    ]
