# Generated by Django 2.2.4 on 2019-09-02 10:01

import apps.company.models.partner
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0005_structure'),
    ]

    operations = [
        migrations.CreateModel(
            name='Partner',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.URLField(blank=True, max_length=255, null=True, verbose_name='URL сайта партнера')),
                ('image', models.ImageField(blank=True, null=True, upload_to=apps.company.models.partner.image_upload_path, verbose_name='Логотип партнера')),
                ('order', models.PositiveIntegerField(default=0, help_text='Чем выше число, тем ниже объект в списке', verbose_name='Порядок')),
            ],
            options={
                'verbose_name': 'Блок (Партнеры)',
                'verbose_name_plural': 'Партнеры (Блоки)',
            },
        ),
    ]
