# Generated by Django 2.2.4 on 2019-09-03 12:04

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0006_partner'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tender',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Название тендера')),
                ('Город', models.CharField(choices=[('construction', 'Строительство'), ('materials', 'Материалы'), ('equipment', 'Оборудование'), ('projecting', 'Проектирование'), ('other', 'Другое')], max_length=100, verbose_name='Категория тендера')),
                ('duties', ckeditor.fields.RichTextField(blank=True, null=True, verbose_name='Обязанности')),
                ('requirements', ckeditor.fields.RichTextField(blank=True, null=True, verbose_name='Требования')),
                ('contacts', ckeditor.fields.RichTextField(blank=True, null=True, verbose_name='Контакты')),
                ('date_start', models.DateTimeField(verbose_name='Срок проведения (начало)')),
                ('date_end', models.DateTimeField(verbose_name='Срок проведения (конец)')),
            ],
            options={
                'verbose_name': 'Тендер',
                'verbose_name_plural': 'Тендеры',
            },
        ),
        migrations.AlterModelOptions(
            name='partner',
            options={'verbose_name': 'Блок (Партнер)', 'verbose_name_plural': 'Партнеры (Блоки)'},
        ),
    ]
