# Generated by Django 2.2.4 on 2019-09-03 12:56

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0007_auto_20190903_1504'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tender',
            old_name='Город',
            new_name='category',
        ),
        migrations.AlterField(
            model_name='tender',
            name='date_end',
            field=models.DateTimeField(default=datetime.datetime.now, verbose_name='Срок проведения (конец)'),
        ),
        migrations.AlterField(
            model_name='tender',
            name='date_start',
            field=models.DateTimeField(default=datetime.datetime.now, verbose_name='Срок проведения (начало)'),
        ),
    ]
