# Generated by Django 2.2.4 on 2019-09-03 13:50

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0008_auto_20190903_1556'),
    ]

    operations = [
        migrations.AddField(
            model_name='tender',
            name='status',
            field=models.BooleanField(default=True, help_text='Активен или нет данный Тендер', verbose_name='Статус'),
        ),
        migrations.AlterField(
            model_name='tender',
            name='date_end',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='Срок проведения (конец)'),
        ),
        migrations.AlterField(
            model_name='tender',
            name='date_start',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='Срок проведения (начало)'),
        ),
    ]
