# Generated by Django 2.2.4 on 2019-09-03 13:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0009_auto_20190903_1650'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tender',
            old_name='status',
            new_name='active',
        ),
    ]
