# Generated by Django 2.2.4 on 2019-09-04 14:12

import apps.company.models.tender
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0010_auto_20190903_1651'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tender',
            name='active',
            field=models.BooleanField(default=True, help_text='Является ли данный Тендер активным?', verbose_name='Активный'),
        ),
        migrations.CreateModel(
            name='TenderFile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Название документа')),
                ('file', models.FileField(blank=True, null=True, upload_to=apps.company.models.tender.file_upload_path, verbose_name='Файл')),
                ('tender', models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='company.Tender')),
            ],
            options={
                'verbose_name': 'Тендер (Файл)',
                'verbose_name_plural': 'Тендеры (Файлы)',
            },
        ),
    ]
