# Generated by Django 2.2 on 2019-04-03 15:27

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SiteSettings',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('site_title', models.CharField(blank=True, help_text='site meta &lt;title&gt;, max 100 chars', max_length=100, null=True, verbose_name='Site title')),
                ('site_description', models.TextField(blank=True, help_text='site meta description, max 150', max_length=150, null=True, verbose_name='Site description')),
                ('site_email', models.EmailField(blank=True, help_text='define site main email', max_length=255, null=True, verbose_name='Site Email')),
                ('site_phone', models.CharField(blank=True, help_text='define site main email, e.g.: +79784447711', max_length=50, null=True, verbose_name='Site Phone')),
            ],
            options={
                'verbose_name': 'Site Settings',
                'verbose_name_plural': 'Site Settings',
            },
        ),
    ]
