# Generated by Django 2.2 on 2019-04-02 13:06

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SiteContactSettings',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='SiteSeoSettings',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('site_title', models.CharField(help_text='site meta <title>, max 100 chars', max_length=100, verbose_name='Site title')),
                ('site_description', models.CharField(help_text='site meta description, max 150', max_length=150, verbose_name='Site description')),
            ],
        ),
    ]
