# Generated by Django 2.2 on 2019-04-04 12:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('settings', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='sitesettings',
            options={'verbose_name': 'Основные настройки сайта', 'verbose_name_plural': 'Основные настройки сайта'},
        ),
    ]
