# Generated by Django 2.2 on 2019-04-11 14:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('settings', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='sitesettings',
            options={'verbose_name': 'Основные настройки сайта', 'verbose_name_plural': 'Основные настройки сайта'},
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='site_facebook',
            field=models.URLField(blank=True, help_text='e.g.: https://facebook.com/monolit', max_length=255, null=True, verbose_name='Facebook'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='site_instagram',
            field=models.URLField(blank=True, help_text='e.g.: https://instagram.com/monolit.crimea/', max_length=255, null=True, verbose_name='Instagram'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='site_telegram',
            field=models.URLField(blank=True, help_text='e.g.: https://t.me/monolitstroit', max_length=255, null=True, verbose_name='Telegram'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='site_vk',
            field=models.URLField(blank=True, help_text='e.g.: https://vk.com/monolit.crimea', max_length=255, null=True, verbose_name='VK (Вконтакте)'),
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='site_email',
            field=models.EmailField(blank=True, help_text='Основной email', max_length=255, null=True, verbose_name='Site Email'),
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='site_phone',
            field=models.CharField(blank=True, help_text='Основной телефон, e.g.: +79784447711', max_length=50, null=True, verbose_name='Site Phone'),
        ),
    ]
