# Generated by Django 2.2 on 2019-04-02 14:19

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('settings', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='sitecontactsettings',
            options={'verbose_name': 'Site Contacts Setting', 'verbose_name_plural': 'Site Contacts Settings'},
        ),
        migrations.AlterModelOptions(
            name='siteseosettings',
            options={'verbose_name': 'Site SEO Setting', 'verbose_name_plural': 'Site SEO Settings'},
        ),
        migrations.AddField(
            model_name='sitecontactsettings',
            name='site_email',
            field=models.EmailField(default=django.utils.timezone.now, help_text='define site main email', max_length=255, verbose_name='Site Email'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='sitecontactsettings',
            name='site_phone',
            field=models.CharField(default=django.utils.timezone.now, help_text='define site main email, e.g.: 79784447711', max_length=50, verbose_name='Site Phone'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='siteseosettings',
            name='site_title',
            field=models.CharField(help_text='site meta &lt;title&gt;, max 100 chars', max_length=100, verbose_name='Site title'),
        ),
    ]
