# Generated by Django 2.2 on 2019-04-02 14:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('settings', '0002_auto_20190402_1719'),
    ]

    operations = [
        migrations.AlterField(
            model_name='siteseosettings',
            name='site_description',
            field=models.TextField(help_text='site meta description, max 150', max_length=150, verbose_name='Site description'),
        ),
    ]
