# Generated by Django 2.2.1 on 2019-05-16 13:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('settings', '0002_auto_20190514_1730'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sitesettings',
            name='site_vk',
            field=models.URLField(blank=True, help_text='e.g.: https://vk.com/monolit.crimea', max_length=255, null=True, verbose_name='VK (ВКонтакте)'),
        ),
    ]
