# Generated by Django 2.2 on 2019-04-02 14:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('settings', '0003_auto_20190402_1727'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sitecontactsettings',
            name='site_email',
            field=models.EmailField(blank=True, help_text='define site main email', max_length=255, verbose_name='Site Email'),
        ),
        migrations.AlterField(
            model_name='sitecontactsettings',
            name='site_phone',
            field=models.CharField(blank=True, help_text='define site main email, e.g.: 79784447711', max_length=50, verbose_name='Site Phone'),
        ),
        migrations.AlterField(
            model_name='siteseosettings',
            name='site_description',
            field=models.TextField(blank=True, help_text='site meta description, max 150', max_length=150, verbose_name='Site description'),
        ),
        migrations.AlterField(
            model_name='siteseosettings',
            name='site_title',
            field=models.CharField(blank=True, help_text='site meta &lt;title&gt;, max 100 chars', max_length=100, verbose_name='Site title'),
        ),
    ]
